Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-07, with the labels that each got.

#1400 Add talkyard
  README.md
Labels: addition, feedback needed, non-free

#1419 Fix OnlyOffice homepage
  README.md
Labels: feedback needed, fix

#1438 removed RSSPBRRY
  README.md
Labels: fix

#1443 removed localpaste
  README.md
Labels: fix

#1444 corrected Demo link for Paste
  README.md
Labels: fix

#1445 added Demo for Stikked
  README.md
Labels: fix

#1446 updated source link for BulletNotes
  README.md
Labels: fix

#1439 Reorder Task Management
  README.md
Labels: fix

#1453 Fix test.js
  test.js
Labels: fix

#1449 Fixed framework specification
  README.md
Labels: fix

#1456 Fix test.js
  test.js
Labels: fix

#1458 Fix contrib command in Makefile
  .github/.mailmap
  AUTHORS.md
  Makefile
Labels: fix

#1457 Fix syntax errors
  README.md
Labels: fix

#1448 added synox/disposable-mailbox
  README.md
Labels: addition

#1450 Added Lazy librarian for Books and Lidarr for Music in Automated
  README.md
Labels: addition

#1463 Added Snibox
  README.md
Labels: addition

#1469 Removing LibreRead
  README.md
Labels: fix
