Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-08, with the labels that each got.

#1378 AlertHub Added
  README.md
Labels: addition

#1452 Added Shopware
  README.md
Labels: addition

#1455 Added outline (Wiki)
  README.md
Labels: addition, feedback needed

#1460 Update contributing
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix, tools

#1467 Add Newspipe and update JARR description
  README.md
Labels: addition, fix

#1471 non-free.md: remove FusionInvoice
  non-free.md
Labels: fix, non-free

#1472 Link Update: Recently moved sessionrecord.com domain to uxlens.com
  non-free.md
Labels: fix, non-free

#1476 Remove Emby from FOSS listing
  README.md
  non-free.md
Labels: fix, non-free

#1481 Duplicated entry
  README.md
Labels: fix
