Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-09, with the labels that each got.

#1470 Add Demo page to simple-dash
  README.md
Labels: fix

#1484 Add: Reaction Commerce
  README.md
Labels: addition

#1486 Deleting Shuup demo link
  README.md
Labels: fix

#1492 Update Homepage username in URL
  README.md
Labels: fix

#1493 Update filemanager's info
  README.md
Labels: fix

#1495 Update NixOS Mailserver Link
  README.md
Labels: fix

#1499 Added FreeScout
  README.md
Labels: addition

#1500 Add Kresus
  README.md
Labels: addition

#1503 Remove SIMPad
  README.md
Labels: fix

#1504 Updated Git Annex Links
  README.md
Labels: fix

#1508 Move cloudron
  README.md
  non-free.md
Labels: fix, non-free

#1502 Reorganise Resource Planning
  README.md
Labels: addition

#1501 add Dante Stories to Blogging Platforms list
  README.md
Labels: addition

#1505 Moving CryptPad to Office-Suites.
  README.md
Labels: fix

#1494 Add Sentry On-Premise
  README.md
Labels: addition

#1509 Replace Libresonic with Airsonic
  README.md
Labels: addition, fix

#1507 removed AmIUnique and NilTalk, inactive sites
  AUTHORS.md
  README.md
Labels: fix

#1513 Add Bookmark Archiver
  README.md
Labels: addition
