Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-06, with the labels that each got.

#1383 Removing Actor.im as it's no longer maintained
  README.md
Labels: fix

#1395 Add Virtual TimeClock to non-free.md
  non-free.md
Labels: addition, non-free

#1392 Created new subsection
  README.md
Labels: addition, fix

#1397 add fathom analytics
  README.md
Labels: addition

#1394 Removed abandoned dashbaords.
  README.md
Labels: fix

#1380 Add Sismics Docs to Document Archiving category
  README.md
Labels: addition

#1382 Updated the Web fonts repository homepage address
  README.md
Labels: fix

#1385 Refactor CONTRIBUTING, PR template, cleanup
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  Dangerfile
  Makefile
  README.md
Labels: fix

#1402 Grammar Fixes for HomeHost
  README.md
Labels: fix

#1403 Update Document Archiving Section
  README.md
Labels: fix

#1412 added link to source for OpenProject
  README.md
Labels: fix

#1404 add hastic
  README.md
Labels: addition

#1391 Add CampaignChain as Hootsuite+Buffer alternative
  README.md
Labels: addition, feedback needed

#1405 Add Shiori https://github.com/RadhiFadlillah/shiori
  README.md
Labels: addition

#1408 added demo link for TaskBoard
  README.md
Labels: fix

#1409 added demo link for Volition
  README.md
Labels: fix

#1410 Add a new 'Clients' link to the entry template + remove Phant (discontinued)
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: feedback needed, fix

#1413 corrceted 404 for PHPOffice
  README.md
Labels: fix

#1414 added link to source for dudle
  README.md
Labels: fix

#1417 Removing MonstaFTP
  README.md
Labels: fix

#1422 Remove Jappix
  README.md
Labels: fix

#1398 Add Maily Form
  README.md
Labels: addition

#1427 added demo link for scrumblr again
  README.md
Labels: fix

#1416 Adding HomelabOS
  README.md
Labels: addition

#1430 corrected a little mess with the links of Lite-Reader
  README.md
Labels: fix

#1433 added homepage for Winds
  README.md
Labels: fix

#1432 added homepage and demo link for Sismics Reader
  README.md
Labels: fix

#1434 Add SIP3.IO Tapir
  README.md
Labels: addition

#1428 removed Creaky Coot
  README.md
Labels: fix

#1426 updated Economizzer
  README.md
Labels: fix

#1425 added Demo link for IHateMoney
  README.md
Labels: fix

#1429 added a Clients-list to ownCloud
  README.md
Labels: fix

#1420 Add Awesome Public Datasets
  README.md
Labels: addition
