Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-05, with the labels that each got.

#1343 Add pretalx to conference management systems
  README.md
Labels: addition

#1353 Added bbPress and attempted to clarify difference w/BuddyPress
  README.md
Labels: addition, fix

#1365 Added simple-dash repo
  README.md
Labels: addition

#1369 Added Ambar to open-source solutions
  README.md
  non-free.md
Labels: addition

#1371 Add homehost (media streaming), split Media streaming category
  README.md
Labels: addition, fix

#1372 Add Accent to the list of self-hosted localization tools
  README.md
Labels: addition

#1374 Fix git-annex url
  README.md
Labels: fix

#1379 Fix location of Mayan to Document archiving section #1299
  README.md
Labels: fix

#1367 ADD formspree
  README.md
Labels: addition

#1368 Added Pleroma to the Social Networks List
  README.md
Labels: addition

#1360 Add üWave to video streaming
  README.md
Labels: addition, feedback needed

#1384 Add Babelfish
  README.md
Labels: addition
