Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-12, with the labels that each got.

#1579 Remove Tellform
  README.md
Labels: fix

#1580 Add boodle
  README.md
Labels: addition

#1581 update BSD licenses
  README.md
Labels: fix, license list

#1573 Add Booking Section
  README.md
Labels: addition, feedback needed

#1583 Remove Laverna (dead), add Joplin (Note-taking and Editors)
  AUTHORS.md
  README.md
Labels: addition, fix

#1584 Rename filemanager to filebrowser
  README.md
Labels: fix

#1586 Add gitlab.com mirror to external links
  README.md
Labels: fix, non-free

#1597 Update "formspree" Demo link
  README.md
Labels: fix
