Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-11, with the labels that each got.

#1556 Fix typo for ipfs.pics
  README.md
Labels: fix

#1539 added PeerTube link
  README.md
Labels: fix

#1554 Fix Silverstrike domain
  README.md
Labels: fix

#1551 Add Expressa to CMS
  README.md
Labels: addition

#1557 Added Organizr to Personal Dashboards
  README.md
Labels: addition

#1528 Add IG Monitoring
  README.md
Labels: addition

#1560 Fix syntax Errors
  README.md
Labels: fix

#1565 Add Heimdall
  README.md
Labels: addition

#1567 Add Gladys
  README.md
Labels: addition

#1566 Adds commento
  README.md
Labels: addition

#1562 Add Ansible-NAS
  README.md
Labels: addition

#1520 Add LocalStack to FaaS
  README.md
Labels: addition, feedback needed, license list

#1561 Add LMS
  README.md
Labels: addition

#1548 Add PhotoPrism (#1)
  README.md
Labels: addition

#1549 add Collabora
  README.md
Labels: addition

#1568 Fix non-free formatting to match README.md
  non-free.md
Labels: fix, non-free

#1569 add gossa
  README.md
Labels: addition

#1522 Add Strapi headless CMS
  README.md
Labels: addition, feedback needed

#1550 Davical License Fix
  README.md
Labels: fix

#1571 Add HRConvert2 to Automation
  README.md
Labels: addition

#1574 Add Domoticz
  README.md
Labels: addition

#1575 add BigBlueButton
  README.md
Labels: addition

#1572 Add remark42
  README.md
Labels: addition
