Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2018-03, with the labels that each got.

#1284 added Tileserver PHP
  README.md
Labels: addition, feedback needed

#1303 Add Redbird reverse proxy
  README.md
Labels: addition

#1309 Add qBittorrent to Peer-to-peer filesharing
  README.md
Labels: addition

#1310 Add orangeforum
  README.md
Labels: addition

#1316 Add SIT Issue Tracker
  README.md
Labels: addition

#1317 Add GolangCI
  README.md
Labels: addition

#1320 Fix several incorrect licenses
  README.md
Labels: fix, license list

#1321 Rename Stash to BitBucket Server
  non-free.md
Labels: fix, non-free

#1322 Fair Source License is not a FLOSS license
  README.md
Labels: fix, license list, non-free

#1323 Added Geekmarks to Bookmarks and Link Sharing
  README.md
Labels: addition

#1324 Add feedmixer to list
  README.md
Labels: addition

#1325 hack.chat is no longer maintained.
  README.md
Labels: fix

#1307 Add TileServer GL
  README.md
Labels: addition

#1326 Friendica project homepage has moved
  README.md
Labels: fix

#1328 remove crush and fix https://github.com/Kickball/awesome-selfhosted/issues/1327
  README.md
Labels: fix

#1336 Remove duplicate link.
  README.md
Labels: fix

#1338 Update demo URL of fileshelter
  README.md
Labels: fix

#1341 Remove IRCAnywhere
  README.md
Labels: fix

#1344 The url of parrot translate has changed
  README.md
Labels: fix

#1329 Added Simple NixOS Mailserver
  README.md
Labels: addition

#1331 Added Gitolite
  README.md
Labels: addition

#1333 Added Web fonts repository
  README.md
Labels: addition

#1334 Add SilverStrike
  README.md
Labels: addition

#1330 Added Kiwi IRC
  README.md
Labels: addition

#1335 Added Jitbit Helpdesk
  non-free.md
Labels: addition, non-free
