Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-01, with the labels that each got.

#1587 Add Jellyfin
  README.md
Labels: addition

#1588 Added xBrowserSync to "Bookmarks and Link Sharing"
  README.md
Labels: addition, feedback needed

#1589 Added OwnPhotos to photo-/videogalleries
  README.md
Labels: addition

#1593 Change Teampass description due to security concerns.
  README.md
Labels: fix

#1595 Add Cadmus - Flat-file blogging
  README.md
Labels: addition

#1598 Add imgproxy
  README.md
Labels: addition, fix

#1602 Update name and website of Bookmark Archiver
  README.md
Labels: fix

#1600 Added Squidex CMS
  README.md
Labels: addition

#1599 Added Polaris music streaming service
  README.md
Labels: addition

#1596 Add Abrays Notes to the list
  README.md
Labels: addition

#1608 update SPF toolbox to new urls
  README.md
Labels: fix
