Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-07, with the labels that each got.

#1735 Update Lychee URLs
  README.md
Labels: fix

#1733 Add ReleaseBell
  README.md
Labels: addition

#1714 Add a socks5 proxy with Telegram-bot and auth
  README.md
Labels: addition

#1721 Changed the link of Modern Paste
  README.md
Labels: curation, feedback needed, fix

#1719 Adding TagTool
  README.md
Labels: addition

#1729 Add DocPHT
  README.md
Labels: addition

#1730 Add imgpush
  README.md
Labels: addition

#1745 Remove Brimir
  README.md
Labels: curation, fix

#1746 Remove Abrays Notes from Notes Section
  README.md
Labels: curation, fix

#1711 Add SOCKS5Engine to Proxy section
  README.md
Labels: addition

#1722 Added PassCheck to Miscellaneous
  README.md
Labels: addition

#1731 Add Rapidbay
  README.md
Labels: addition

#1732 Add Contao
  README.md
Labels: addition

#1736 Add Kong to the API management list
  README.md
Labels: addition

#1739 Added Lemmy (Reddit clone)
  README.md
Labels: addition

#1758 Edit: Better description and right name for Riot.im
  README.md
Labels: fix

#1756 update mattermost, icecoder, HTPC-Manager, textpad URLs
  README.md
Labels: curation, fix

#1752 Fix django-wiki demo URL.
  README.md
Labels: fix

#1742 Add fibridge file sharing
  README.md
Labels: addition

#1743 Add nominatim
  README.md
Labels: addition
