Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-03, with the labels that each got.

#1637 Remove Apache Bloodhound (discontinued)
  README.md
Labels: fix

#1643 Fix typo
  README.md
Labels: fix

#1615 Adds Fugacious to pastebins
  README.md
Labels: addition

#1625 Add RosarioSIS
  README.md
Labels: addition

#1626 Add Gotify
  README.md
Labels: addition

#1628 Add @jessfraz's s3server
  README.md
Labels: addition

#1630 Add PixelFed to list.
  README.md
Labels: addition

#1635 Add liteshort
  README.md
Labels: addition

#1627 Added AfterLogic WebMail Lite to Webmail clients.
  README.md
Labels: addition

#1646 Delegate 'Continuous Integration' section to awesome-sysadmin
  README.md
Labels: fix

#1658 .travis.yml: upgrade ruby to v2.6.2
  .travis.yml
Labels: fix, tools

#1611 ASTPP
  README.md
Labels: addition, feedback needed

#1633 Updated omgnata entry as the name + homepage have changed.
  README.md
Labels: fix

#1641 Add bin
  README.md
Labels: addition, license list

#1644 added trilium
  README.md
Labels: addition

#1650 Add code-server
  README.md
Labels: addition

#1652 CONTRIBUTING.md: link to help wanted/maintenance issues
  .github/CONTRIBUTING.md
Labels: fix
