Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-06, with the labels that each got.

#1694 Add DecSync #1691
  README.md
Labels: addition, feedback needed

#1696 Add Open Streaming Platform
  README.md
Labels: addition

#1701 Add KISSS
  README.md
Labels: addition

#1713 Syntax fixes
  README.md
Labels: fix

#1700 Add django-todo to README
  README.md
Labels: addition

#1702 Add gerbera
  README.md
Labels: addition

#1709 Add photonix
  README.md
Labels: addition

#1716 Add missing full stop
  README.md
Labels: fix

#1715 Added OpenOLAT
  README.md
Labels: addition

#1718 update Traccar source code
  README.md
Labels: fix

#1720 Merge the two WebMail Lite entries.
  README.md
Labels: fix

#1723 Makefile: improve automated maintenance tasks
  Makefile
  README.md
Labels: curation, fix, tools
