Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-08, with the labels that each got.

#1764 Update LazyLibrarian URL
  README.md
Labels: fix

#1762 Move Gossa to web based file managers.
  README.md
Labels: fix

#1771 fixed small errors
  README.md
Labels: fix

#1759 Fix ppen typo
  README.md
Labels: fix

#1776 Leed URL updated
  README.md
Labels: fix

#1774 Remove/Edited link from multiple sites
  README.md
Labels: curation, fix

#1738 Adds a URL Shortener
  README.md
Labels: addition

#1744 Added rss-fulltext-proxy
  README.md
Labels: addition

#1749 added indico, conference management suite
  README.md
Labels: addition

#1757 Add Teedy.io to Document Management
  README.md
Labels: addition

#1761 Add Dnote to Note-taking and Editors
  AUTHORS.md
  README.md
Labels: addition

#1769 Weaviate
  README.md
Labels: addition

#1770 Add chasquid to the Email/MTA section
  README.md
Labels: addition

#1755 Added new url shortener (Simple-URL-Shortener)
  README.md
Labels: addition

#1779 [irc] Add Glowing Bear
  README.md
Labels: fix

#1778 Travis Test
  .travis.yml
  tests/test.js
Labels: tools

#1782 Update/Remove Links
  README.md
Labels: curation, fix

#1785 Update .travis.yml
  .travis.yml
  tests/test.js
Labels: fix, tools

#1783 Add feed2toot
  README.md
Labels: addition

#1786 Fix syntax errors.
  README.md
Labels: fix

#1791 Remove Multiple Site/Demo URLs
  README.md
Labels: curation, fix

#1795 Remove Telescope
  README.md
Labels: curation, fix
