Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-10, with the labels that each got.

#1828 Update Paperwork links
  README.md
Labels: fix

#1834 Updated Links to new Repo URL
  README.md
Labels: fix

#1838 Remove some dead links and projects
  README.md
Labels: curation, fix

#1775 Add Cloud Computer
  README.md
Labels: addition

#1789 Add ActiveWorkflow
  README.md
Labels: addition

#1803 Add Hauk
  README.md
Labels: addition

#1807 Add GoatCounter
  README.md
Labels: addition

#1823 Add Shlink project to the list.
  README.md
Labels: addition

#1830 Add ngircd
  README.md
Labels: addition

#1835 Add Homer
  README.md
Labels: addition

#1836 Add minetest game
  README.md
Labels: addition

#1837 Add EveryDocs
  README.md
Labels: addition, feedback needed

#1839 Updated readme for Firefly III
  README.md
Labels: fix

#1800 Added Ackee
  README.md
Labels: addition

#1801 Add ML Workspace
  README.md
Labels: addition

#1812 Updated grocy links & description
  README.md
Labels: fix

#1840 minor fix: Correct Plume's programming langauge to rust from ruby
  README.md
Labels: fix

#1802 Add Opensapdes/piqueserver in Games
  README.md
Labels: addition

#1806 Add Coral - a better commenting experience
  README.md
Labels: addition

#1815 Added Moon software
  non-free.md
Labels: addition, non-free

#1816 Add FullHelp.com
  non-free.md
Labels: addition, non-free

#1833 Add Accelerated Text to Automation section
  README.md
Labels: addition

#1818 Updated Links to Open Streaming Platform
  README.md
Labels: fix

#1844 added n8n to automation
  README.md
Labels: addition

#1846 Update devShort demo link
  README.md
Labels: fix

#1845 Updated links for the Newspipe project
  README.md
Labels: fix

#1855 fix: Bennedetto typo
  README.md
Labels: fix

#1848 Added Legend of the Green Dragon
  README.md
Labels: addition

#1813 Full-Text RSS from fivefilters.org
  README.md
Labels: addition

#1849 Added UVDesk Community edition
  README.md
Labels: addition

#1851 Add TeslaMate
  README.md
Labels: addition

#1841 adding bluecherry nvr
  README.md
Labels: addition

#1819 Added sipXcom to SIP/IPPBX
  README.md
Labels: addition, feedback needed

#1854 Update Wazo
  README.md
Labels: fix

#1857 Add bitwarden_rs to password managers
  README.md
Labels: addition

#1861 Highlight Bitwarden relies on closed source
  README.md
Labels: fix, non-free
