Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-02, with the labels that each got.

#1609 Remove Bookie - inactive project
  README.md
Labels: fix

#1610 Remove SemanticScuttle - inactive project
  README.md
Labels: fix

#1601 Update non-free.md
  non-free.md
Labels: fix, non-free

#1614 Add EspoCRM
  README.md
Labels: addition

#1616 Added XBackBone
  README.md
Labels: addition

#1619 add Espial
  README.md
Labels: addition

#1622 Add DockSTARTer
  README.md
Labels: addition

#1624 Added ProjeQtOr to list of Project Management tools.
  README.md
Labels: addition

#1631 Removed SSilence/notes because repo does not exist
  README.md
Labels: fix
