Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-12, with the labels that each got.

#1887 adding titra.io to the project management category
  README.md
Labels: addition

#1893 Remove/Update dead links
  README.md
Labels: fix

#1895 Add Davis
  README.md
Labels: addition

#1898 Added demo link for Mediawiki.
  README.md
Labels: fix

#1900 Add Kantree
  non-free.md
Labels: addition, non-free

#1867 Add inlets.dev
  README.md
Labels: addition

#1889 Added CKAN
  README.md
Labels: addition

#1891 Adding torrents.csv and KeePassXC.
  README.md
Labels: addition

#1892 Adds Canvas as a self-hosted blog platform
  README.md
Labels: addition

#1897 Added Writing Text Editor
  README.md
Labels: addition

#1899 add gonic (music streaming server)
  README.md
Labels: addition

#1904 Added Nullboard to "Task management/To-do lists"
  README.md
Labels: addition

#1905 Add PhotoStructure
  non-free.md
Labels: addition, non-free

#1906 Add Groupboard
  non-free.md
Labels: addition, non-free

#1913 Add JD Esurvey
  README.md
Labels: addition

#1915 Add Channels DVR Server
  non-free.md
Labels: addition, non-free

#1885 Add CharjaBox to selfhosting solutions
  README.md
Labels: addition

#1912 Fix TeslaMate syntax
  README.md
Labels: fix

#1914 Updated XBackBone description.
  README.md
Labels: addition

#1907 Remove some dead links/unmaintained projects
  README.md
Labels: curation, feedback needed, fix

#1896 Added Freshlytics to Analytics
  README.md
Labels: addition

#1903 Add Rudder
  README.md
Labels: addition

#1918 link to Fathom GitHub repository as website is not about open-source …
  README.md
Labels: fix, non-free

#1920 Fix Typo
  README.md
Labels: fix

#1922 Add gShort
  README.md
Labels: addition

#1923 Add Re:Backlogs
  README.md
Labels: addition

#1924 Added krakenD
  README.md
Labels: addition

#1921 Added Spree Commerce to list of eCommerce systems
  README.md
Labels: addition

#1925 Update to most recent tagline
  README.md
Labels: addition
