Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2019-05, with the labels that each got.

#1647 Fix duplicate and broken links (part 1)
  .travis.yml
  README.md
Labels: fix, tools

#1656 Updated simple-dash
  README.md
Labels: fix

#1664 Add Filestash
  README.md
Labels: addition

#1693 Update maildrop link
  README.md
Labels: fix

#1692 update code-server url
  README.md
Labels: fix

#1668 Added Helpy
  README.md
Labels: addition

#1678 Update dead demo URL
  README.md
Labels: fix

#1681 docs(readme): add Leon personal assistant
  README.md
Labels: addition

#1682 Add devShort
  README.md
Labels: addition

#1685 Add fava.
  README.md
Labels: addition

#1686 Add Pomerium.
  README.md
Labels: addition

#1695 remove some unmaintained projects, update URLs that have changed
  README.md
Labels: curation, fix

#1699 Update link and license for ShinobiCE
  README.md
Labels: fix

#1698 Tests: add a script to check last commit dates of github repositories listed in README.md
  .github/join-chat.svg
  .travis.yml
  tests/Dangerfile
  tests/check-github-commit-dates.py
  tests/test.js
Labels: curation, fix, tools

#1670 Add Galleries
  README.md
Labels: addition

#1706 Remove some unmaintained projects
  README.md
Labels: curation, fix

#1707 remove wheatbin (unmaintained, never was)
  README.md
Labels: curation, fix
