Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-11, with the labels that each got.

#2293 fixed a couple very minor typos
  README.md
Labels: fix

#2297 Fixing canvas link
  README.md
Labels: fix

#2298 Remove Droppy and Kandan from Awesome-selfhosted list
  README.md
Labels: curation

#2284 Add oddmuse to wiki
  README.md
Labels: addition

#2296 Add filebrowser (Web based file managers)
  README.md
Labels: addition

#2299 Add Zipline
  README.md
Labels: addition

#2310 Moving Sharetribe to non-free.md Fix #2283
  README.md
  non-free.md
Labels: fix, non-free

#2312 Removed Xbox from Jellyfin client list.
  README.md
Labels: fix

#2290 Add goeland to RSS/Atom automation
  README.md
Labels: addition

#2301 Added Podgrab to Automation
  README.md
Labels: addition

#2321 Update non-free.md
  non-free.md
Labels: fix

#2322 Add Tinode
  README.md
Labels: addition

#2306 Add Gancio to Polls and Events
  README.md
Labels: addition
