Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-07, with the labels that each got.

#2150 Update README.md
  README.md
Labels: fix

#2123 Add Trusted-CGI
  README.md
Labels: addition

#2129 Rename AnsiMail to Excision Mail
  README.md
Labels: fix

#2131 Fix version typos
  README.md
Labels: fix

#2132 Rename of Sharelatex to Overleaf
  README.md
Labels: fix

#2138 Update sist2 demo website
  README.md
Labels: fix

#2139 Edit link for "RSS2EMail"
  README.md
Labels: fix

#2140 Updating links for HomelabOS
  README.md
Labels: fix

#2126 Add ReducePy to URL shorteners
  README.md
Labels: addition

#2122 Add moOde audio player
  README.md
Labels: addition

#2149 Add Pagure
  README.md
Labels: addition

#2148 Add Hiccup
  README.md
Labels: addition

#2147 Add myDrive
  README.md
Labels: addition

#2134 Add Family Accounting Tool
  README.md
Labels: addition

#2155 add demo link for jellyfin and update description
  README.md
Labels: fix

#2156 Remove Polar Bookself
  README.md
Labels: curation, fix, non-free

#2161 Update README, Firefly III now requires PHP 7.4
  README.md
Labels: fix

#2164 Update Shopware repository
  README.md
Labels: fix

#2165 Add Navidrome demo site
  README.md
Labels: fix

#2168 Remove Puffin, as it is abandoned
  README.md
Labels: curation, fix

#2172 fix syntax error Gitpod
  README.md
Labels: fix
