Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-08, with the labels that each got.

#2157 add Meetable
  README.md
Labels: addition

#2160 add wbo
  README.md
Labels: addition

#2183 Fixed links for Reactive Resume
  README.md
Labels: fix

#2169 Add Quizmaster to Games
  README.md
Labels: addition

#2184 [UPDATE] Digital-Currency demo website updated
  README.md
Labels: fix

#2127 Add lazylead
  README.md
Labels: addition

#2142 Add BlueMind groupware
  README.md
Labels: addition

#2143 Add PassWall
  README.md
Labels: addition

#2151 Add Postwoman.io to API management
  README.md
Labels: addition

#2162 Added Chartbrew to the Business Int category
  README.md
Labels: addition

#2170 Add rss2twtxt and twtxt.net
  README.md
Labels: addition

#2189 Add reader to Feed Readers
  README.md
Labels: addition

#2190 Remove unmaintained projects
  README.md
Labels: curation

#2001 Add notice under link shorteners to prevent link rot.
  README.md
Labels: discussion, feedback needed

#2182 Add Offen to Analytics
  README.md
Labels: addition

#2185 Add Neko to Gateways and Terminal Sharing
  README.md
Labels: addition

#2187 Add PushBits to Custom communication systems
  README.md
Labels: addition

#2195 Renamed riot.im to Element, updated links and added https
  README.md
Labels: fix

#2200 Add newsdash to Feed Readers
  README.md
Labels: addition

#2188 Add HttPlaceholder to IDE/Tools
  README.md
Labels: addition

#2198 Fix syntax errors
  README.md
Labels: curation, fix
