Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-09, with the labels that each got.

#2204 Add Feedpushr to Feed Readers
  README.md
Labels: addition

#2208 Add Readflow to Read it Later Lists
  README.md
Labels: addition

#2210 Add NymphCast to Multimedia Streaming
  README.md
Labels: addition

#2212 Added Umami in Web Analytics
  README.md
Labels: addition

#2213 Updated the Weaviate listing
  README.md
Labels: curation

#2202 Fix URL checks/remove unmaintained projects
  README.md
Labels: curation, fix

#2199 Travis test
  .travis.yml
  tests/test.js
Labels: tools

#2217 Postwoman renamed to Hoppscotch
  README.md
Labels: fix

#2228 Remove tagtool - it's no longer maintained
  README.md
Labels: curation

#2222 Pull Request Template/README.md: clarify ⚠ symbol meaning, clarify formatting guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: fix

#2158 Add JupyterLab
  README.md
Labels: addition

#2223 Add Oragono to section IRC
  README.md
Labels: addition
