Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-04, with the labels that each got.

#2000 Update URL for DashMachine
  README.md
Labels: fix

#2031 Add PiGallery2
  README.md
Labels: addition

#2019 Add Photo Stream
  README.md
Labels: addition

#2030 Update README.md
  README.md
Labels: addition

#2037 Add "Resume Builders" Section, Add "Reactive Resume"
  README.md
Labels: addition

#2042 Fixed dead Firefox Auth/Content/Sync server links
  README.md
Labels: curation, fix

#2025 Add/Remove/Edit multiple Projects
  README.md
Labels: addition, fix

#2043 add Sorcia
  README.md
Labels: addition

#2040 Added Appwrite
  README.md
Labels: addition

#2053 Music cleanup
  README.md
Labels: curation, fix

#2049 Update Navidrome links
  README.md
Labels: fix

#2044 Add PostHog to analytics
  README.md
Labels: addition

#2003 Added website for Komga
  README.md
Labels: fix

#2002 lufi moved
  README.md
Labels: fix

#2033 Change docspell url and headline
  README.md
Labels: fix

#2069 Rename Tapir to SIP3 and add Demo link
  README.md
Labels: fix

#2072 addressing URL checks from 2020-04-07 monthly check
  README.md
Labels: fix
