Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-06, with the labels that each got.

#2100 Add graph-vl into other section
  README.md
Labels: addition

#2090 Add FLAP
  README.md
Labels: addition, feedback needed

#2086 Add `mkaczanowski/pastebin` to the pastebin subsection
  README.md
Labels: addition

#2078 Add Glosa
  README.md
Labels: addition

#2113 docs: update link to MiAOU to use new domain
  README.md
Labels: fix

#2121 Removed Newebe
  README.md
Labels: curation, fix

#2088 Add wreeto to Wikis
  README.md
Labels: addition

#2124 Add demo link to m1k1o/blog.
  README.md
Labels: fix
