Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-10, with the labels that each got.

#2233 Add Pizzly to API Management
  README.md
Labels: addition

#2221 fix language/platform tag for typescript entries
  README.md
Labels: fix

#2220 replace Clojure language/platform tags with Java
  README.md
Labels: fix

#2230 Add Radium to Video Streaming
  README.md
Labels: addition

#2236 Remove IG Monitoring
  README.md
Labels: curation

#2247 Move Cerb to non-free.md
  README.md
  non-free.md
Labels: fix, non-free

#2231 Remove firefox send from peer-to-peer filesharing
  README.md
Labels: curation

#2232 Add pasty to pastebins
  README.md
Labels: addition

#2234 Removing "Synereo"
  non-free.md
Labels: curation, non-free

#2238 Add Plausible to web analytics
  README.md
Labels: addition

#2239 Add Kindmetrics to web analytics
  README.md
Labels: addition

#2240 Add Microgit to Project Management
  README.md
Labels: addition

#2242 Added Typesense to Search Engines
  README.md
Labels: addition

#2245 Add Ptorx and Move Anonaddy to Complete solusions
  README.md
Labels: addition, fix

#2248 Add Papercups to Custom communication systems
  README.md
Labels: addition

#2250 add Dolibarr to enterprise resource planning section
  README.md
Labels: addition

#2249 Add Erxes to Ticketing
  README.md
Labels: addition

#2141 Add OSPOS
  README.md
Labels: addition

#2224 fix indentation for rss2twtxt
  README.md
Labels: fix

#2241 Fix seafile license
  README.md
Labels: fix

#2252 Updated Hastebin's information
  README.md
Labels: curation, fix

#2260 awesome-analytics-merge: link to a-analytics
  README.md
Labels: curation

#2254 awesome-analytics-merge: block 1
  README.md
Labels: curation

#2255 awesome-analytics-merge: block 2
  README.md
Labels: curation

#2256 awesome-analytics-merge: block 3
  README.md
Labels: curation

#2257 awesome-analytics-merge: block 4
  README.md
Labels: curation

#2258 awesome-analytics-merge: block 5
  README.md
Labels: curation

#2259 awesome-analytics-merge: block 6
  README.md
Labels: curation

#2215 cleanup/streamline/improve automated checks:
  .travis.yml
  Makefile
  README.md
Labels: tools

#2272 remove miniproxy
  README.md
Labels: curation

#2271 update GNU social source code link
  README.md
Labels: fix

#2270 non-free.md: Delete Federated Identity/Authentication section
  non-free.md
Labels: curation, non-free

#2261 Add MeTube to Automation
  README.md
Labels: addition

#2268 Add Sshwifty to Gateways and terminal sharing
  README.md
Labels: addition

#2269 Adding uTask to Automation
  README.md
Labels: addition

#2263 Add "Demo" Link to "openHAB" in section "IoT"
  README.md
Labels: fix

#2267 Updated Goodwork Demo
  README.md
Labels: fix

#2262 Added StackStorm to Automation Section
  README.md
Labels: addition

#2278 Improving readability
  README.md
Labels: curation, fix

#2264 Add Kloudless to Software Development (non-free)
  non-free.md
Labels: addition, non-free

#2285 Remove demo site for fibridge
  README.md
Labels: fix

#2276 Add 2FAuth to Misc/Other
  README.md
Labels: feedback needed

#2286 Add Mobilizon to Polls and Events
  README.md
Labels: addition

#2274 Add Isotope, HyperKitty, Postorius, LBRY
  README.md
Labels: addition

#2281 Added demo link for minimalist-web-notepad
  README.md
Labels: fix

#2280 Fix category and note formatting.
  README.md
Labels: fix

#2279 Add Send to Peer-To-Peer Filesharing.
  README.md
Labels: addition
