Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-05, with the labels that each got.

#2016 Added b2evolution
  README.md
Labels: addition

#2063 xandikos doesn't support WebDAV
  README.md
Labels: fix

#2058 Add goploader in Single-click/drag-n-drop upload
  README.md
Labels: addition

#1999 Add linkding
  README.md
Labels: addition

#2065 Added FusionAuth to list
  non-free.md
Labels: addition, non-free

#2066 Add Zusam
  README.md
Labels: addition

#2051 Added Share
  README.md
Labels: addition

#2046 Add Net64+ to games
  README.md
Labels: addition, feedback needed

#2067 Updated home page of Newspipe
  README.md
Labels: fix

#2071 Add Shynet (web analytics)
  README.md
Labels: addition

#2075 Adding Shhh to "Custom communication systems".
  README.md
Labels: addition

#2015 Added YoutubeDL-Material
  README.md
Labels: addition

#2048 Add Maza
  README.md
Labels: addition

#2052 list NextCloudPi (was: Update README.md)
  README.md
Labels: addition

#2056 Add OFBiz to ERP section
  README.md
Labels: addition

#2064 Update non-free.md (add analytics: userTrack)
  non-free.md
Labels: addition, non-free

#1995 Added Typemill to the list of cms
  README.md
Labels: addition

#1989 Add SimpleLogin to email and Federated Identity section
  README.md
Labels: addition

#2017 Updated the outdated source link of mailcow
  README.md
Labels: fix

#2050 Added SocksBin, a terminal based pastebin
  README.md
Labels: addition

#2061 Add betanin to "Automation"
  README.md
Labels: addition

#2079 Update Cozy : delete mail mention
  README.md
Labels: fix

#2074 Add ubookmark to bookmarks/link sharing
  README.md
Labels: addition

#2087 Fix URL checks, remove unmaintained projects
  README.md
Labels: curation, fix

#2096 Update GoatCounter license and tagline
  README.md
Labels: fix

#2098 Updated Duetapp Demo Link
  non-free.md
Labels: fix, non-free

#2089 add Gitpod Self-Hosted to non-free#software-development.
  non-free.md
Labels: addition, non-free

#2080 added PurritoBin encrypted pastebin service
  README.md
Labels: addition

#2091 Add Hakatime
  README.md
Labels: addition

#2093 Add Fussel Gallery
  README.md
Labels: addition

#2099 Gps/geo2tz
  README.md
Labels: addition

#2082 Add feedka to Poll and Events
  README.md
Labels: addition

#2108 Software end-of-lifed, no longer maintained
  README.md
Labels: curation, fix

#2083 add node-virtual-gamepads
  README.md
Labels: addition

#2105 change Icecast 2 sourcecode url
  README.md
Labels: fix
