Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-02, with the labels that each got.

#1971 Clean up list. (Revised)
  .travis.yml
  README.md
Labels: fix

#1963 Add filite
  README.md
Labels: addition

#1966 Add DashMachine to Personal Dashboards
  README.md
Labels: addition

#1965 Add sist2
  README.md
Labels: addition

#1964 Add Personal Management System to Personal Dashboards
  README.md
Labels: addition, feedback needed

#1980 Fix License issues
  README.md
Labels: curation, fix, license list

#1979 Fix Multiple Syntax Errors
  README.md
Labels: curation, fix

#1974 Included Papermerge - Open Source Document Management System.
  README.md
Labels: addition

#1958 Add Digital-Currency
  README.md
Labels: addition

#1977 Travis test
  .travis.yml
  tests/test.js
Labels: tools

#1981 Fix non-free links
  non-free.md
Labels: fix, non-free

#1976 Add Snapcast
  README.md
Labels: addition

#1982 Remove DAVDroid Client #1960
  README.md
Labels: curation, fix

#1975 Add Reminiscence
  README.md
Labels: addition

#1985 Add vikunja to task management
  README.md
Labels: addition

#1983 Add Misskey under Social Networks and Forums
  README.md
Labels: addition

#1968 Added Atheos, continuing Codiad Development
  README.md
Labels: addition

#1986 Add Custom Communication Servers
  README.md
Labels: addition

#1990 Add Mozilla WebThings Gateway
  README.md
Labels: addition
