Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-03, with the labels that each got.

#2021 Remove devShort
  README.md
Labels: curation, fix

#2035 Replace Maily-Form with MailyGo
  README.md
Labels: fix

#2018 Add Photoview
  README.md
Labels: addition

#2020 Add Mango
  README.md
Labels: addition

#2026 Add AnonAddy to Webmail clients
  README.md
Labels: addition

#2027 Add SyncTube
  README.md
Labels: addition
