Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2020-01, with the labels that each got.

#1933 Updated Huginn to use direct URL
  README.md
Labels: fix

#1944 Remove nimbus
  README.md
Labels: curation

#1940 Add Komga
  README.md
Labels: addition

#1948 Update linx-server entry
  README.md
Labels: fix

#1949 Fix CumulusClips demo link
  README.md
Labels: fix

#1957 Fix most of the issues when running awesome_bot
  .travis.yml
  Makefile
  README.md
Labels: fix

#1927 Add docspell
  README.md
Labels: addition

#1931 Update non-free.md
  non-free.md
Labels: addition, non-free

#1932 Add cState
  README.md
Labels: addition

#1935 Add Corteza
  README.md
Labels: addition

#1950 Add Hasura under API Management
  AUTHORS.md
  README.md
Labels: addition

#1947 Add m1k1o/blog
  README.md
Labels: addition

#1943 Add Padloc
  README.md
Labels: addition

#1955 Remove unmaintained projects from category "Photo and Video Galleries"
  README.md
Labels: curation, feedback needed, fix
