Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-04, with the labels that each got.

#2448 Add MediaCMS to Video Streaming
  README.md
Labels: addition

#2449 Add Appsmith to IDE/Tools
  README.md
Labels: addition

#2455 Add Deskpro
  non-free.md
Labels: addition, non-free

#2465 Add Kavita to Personal e-book management software section
  README.md
Labels: addition

#2474 Add ExBin to Pastebins
  README.md
Labels: addition

#2478 Remove Koding from IDE/Tools
  README.md
Labels: curation, fix

#2489 Updated urls for pasty pastbin
  README.md
Labels: fix

#2443 Add form.io to API Management
  README.md
Labels: addition

#2477 Add SFTPGo
  README.md
Labels: addition

#2493 remove FreeNAS (discontinued, TrueNAS not Free software anymore)
  README.md
Labels: curation, fix, non-free

#2468 Remove Tipboard, add Smashing
  README.md
Labels: addition, curation

#2471 added baserow to automation
  README.md
Labels: addition

#2479 Add Localizer to Localization
  README.md
Labels: addition

#2470 Add Yeti-Switch project - Opensource SIP softswitch and billing
  README.md
Labels: addition

#2485 New Genealogy section - Including Genea.app
  README.md
Labels: addition

#2488 Add Jina open-source search framework
  README.md
Labels: addition

#2494 Add HomeGallery to Photo and Video Galleries
  README.md
Labels: addition

#2497 Add Lowdefy to IDE/Tools
  README.md
Labels: addition

#2501 Adds Chaskiq to Custom communication systems
  README.md
Labels: addition
