Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-05, with the labels that each got.

#2476 Add Databunker
  README.md
Labels: addition

#2503 Add Yetishare to File Scripts & Reservo to Image Scripts - Non Free
  non-free.md
Labels: addition, non-free

#2513 Add Orchest to Misc/Other
  README.md
Labels: addition

#2491 Add image-uploader for file uploaders
  README.md
Labels: addition

#2509 Add Flextype Content Management System
  README.md
Labels: addition

#2511 Add I, Librarian to Document Management
  README.md
Labels: addition

#2524 Renamed bitwarden_rs to Vaultwarden
  README.md
Labels: curation, fix

#2529 Replace linx-server with maintained fork
  README.md
Labels: curation, fix

#2520 Add ydl_api to Automation
  README.md
Labels: addition

#2510 game Zero-K
  README.md
Labels: addition

#2512 Add Notea
  README.md
Labels: addition

#2521 Add LogPaste to pastebins
  README.md
Labels: addition

#2522 Adds Dashy to Personal Dashboards
  README.md
Labels: addition

#2514 Add MTA:SA to Game Servers
  README.md
Labels: addition

#2523 Added Aimeos to CMS / E-Commerce
  README.md
Labels: addition

#2525 Added EasyQuickImport to Money, Budgeting and Management
  README.md
Labels: addition, feedback needed, non-free

#2526 Add ChiefOnboarding to Automation
  README.md
Labels: addition

#2532 Add Spacebin to pastebins
  README.md
Labels: addition
