Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-10, with the labels that each got.

#2641 Add blink to URL shorteners
  README.md
Labels: addition

#2667 Adds Gravitational's Teleport to Gateways and Terminal Sharing
  README.md
Labels: addition, feedback needed

#2673 Add ToolJet to Software Development - IDE & Tools category
  README.md
Labels: addition

#2690 Add GlitchTip to ticketing
  README.md
Labels: addition

#2692 Add Mejiro photo publishing application
  README.md
Labels: addition

#2693 Added Snippet Box to Pastebins
  README.md
Labels: addition

#2696 Add Exadel CompreFace to Automation
  README.md
Labels: addition, feedback needed

#2701 Remove Boostnote
  README.md
Labels: curation

#2676 Add euterpe to Media Streaming - Audio Streaming
  README.md
Labels: addition

#2685 Add QuickShare to File Transfer- Single click...
  README.md
Labels: addition

#2682 Add SheetAble to Multimedia Streaming
  README.md
Labels: addition

#2687 Add DeepfakeHTTP to Software Development - UX Testing
  README.md
Labels: addition

#2688 Added interaapps/pastefy as a Pastebin
  README.md
Labels: addition

#2699 Add Raveberry to Media Streaming - Audio Streaming
  README.md
Labels: addition

#2728 Update non-free.md
  non-free.md
Labels: non-free

#2735 Updates link to the live demo for Dashy
  README.md
Labels: fix
