Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-01, with the labels that each got.

#2317 Add IHateToBudget to Money, Budgeting and Management
  README.md
Labels: addition

#2316 Add Damselfly to Photo and Video Galleries
  README.md
Labels: addition

#2339 Add DailyTxT to Misc/Other
  README.md
Labels: addition

#2341 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#2344 Firefox Accounts Server
  README.md
Labels: addition

#2329 Add Conduit to Custom communication systems
  README.md
Labels: addition

#2349 Update WebThings description and links
  README.md
Labels: fix

#2352 Fixed broken urls for Convos
  README.md
Labels: fix

#2355 Update location of liteshort
  README.md
Labels: fix

#2362 Added "Demo" link to "Volition" in section "Task management/To-do li…
  README.md
Labels: fix

#2363 Update URL for Paperless
  README.md
Labels: fix

#2365 Update FreedomBox links and license
  README.md
Labels: fix

#2366 Remove Piratebox from Self-hosting Solutions
  README.md
Labels: curation, fix

#2367 Fix filebrowser description
  README.md
Labels: fix

#2372 Removing Booked from Booking and Scheduling.
  README.md
Labels: curation, fix, non-free

#2371 Remove Darwin Streaming Server from Audio Streaming
  README.md
Labels: curation, fix

#2340 Add FireShare
  README.md
Labels: addition

#2350 Add Olaris video streaming server to video streaming section
  README.md
Labels: addition

#2368 Add YourSpotify to Personal Dashboards category
  README.md
Labels: addition

#2354 add paper{s}pace to Document Management
  README.md
Labels: addition

#2343 Add Tabby to Money, Budgeting and Management
  README.md
Labels: addition

#2381 Replaces CodiMD with HedgeDoc b/c name change
  README.md
Labels: fix

#2384 Removed HipChat from non-free
  non-free.md
Labels: curation, non-free

#2369 add paperless-ng
  README.md
Labels: addition

#2292 Add DebOps to Complete solutions
  README.md
Labels: addition

#2327 Add SiteInspector to Automation
  README.md
Labels: addition

#2345 Added OpenRemote new open source IoT Platform
  README.md
Labels: addition

#2351 Add Taskord to Task management/To-do lists
  README.md
Labels: addition

#2374 Add Patrowl
  README.md
Labels: addition

#2379 Add atman (non-free)
  non-free.md
Labels: addition, non-free

#2382 Add blocky to DNS
  README.md
Labels: addition

#2391 Fix userTrack demo link
  non-free.md
Labels: fix, non-free
