Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-07, with the labels that each got.

#2589 Add Teddit to Social Networks
  README.md
Labels: addition

#2587 Remove Feedbin
  README.md
Labels: curation

#2581 Added Gibbon to Learning and Courses
  README.md
Labels: addition

#2572 Add Rustpad to Office Suites
  README.md
Labels: addition

#2571 Add Jmz Home Proxy to Personal Dashboards
  README.md
Labels: addition

#2597 Add Horahora to Category Archiving and Digital Preservation
  README.md
Labels: addition

#2594 Add "MailForm" to category "Mail Delivery Agents"
  README.md
Labels: addition

#2578 Add Flame to Personal Dashboards
  README.md
Labels: addition

#2574 Add budgetzero to Money, Budgeting and Management section
  README.md
Labels: addition

#2569 Add Lancache to Misc/Other
  README.md
Labels: addition

#2607 Fix syntax, standardize casing, make project names unique, remove sapioit/URL-shortener
  README.md
Labels: curation, fix

#2608 Fix category headings
  README.md
Labels: curation, fix

#2568 Add Dogbin to list of pastebins
  README.md
Labels: addition

#2579 Add Snikket to XMPP servers
  README.md
Labels: addition

#2582 Added Passky
  README.md
Labels: addition

#2606 Added 66Analytics to Non-free Analytics
  non-free.md
Labels: addition, non-free

#2614 Update Photo Stream entry
  README.md
Labels: addition

#2611 Add easyindie.app
  README.md
Labels: addition, feedback needed

#2595 Add "Cloudbox" To Category "Self-hosting Solutions"
  README.md
Labels: addition

#2617 Fixes and Updates for July monthly checks
  README.md
Labels: curation, fix

#2620 flatten table of contents + syntax and case fixes
  README.md
Labels: fix, tools

#2621 standardize section headers:
  README.md
Labels: fix, tools

#2622 fix anchor/inter-section links
  README.md
Labels: fix

#2623 Fix the sourcecode URLs for many of my (prologic) Self Hosted Apps
  README.md
Labels: fix

#2615 Add Crater
  README.md
Labels: addition

#2535 Update Torrents.csv link
  README.md
Labels: curation, feedback needed, fix, help wanted

#2604 Add Track Awesome List external link
  README.md
Labels: curation
