Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-09, with the labels that each got.

#2650 fix Docstore link to be more specific
  README.md
Labels: fix

#2652 Update RetroShare URL in README.md
  README.md
Labels: fix

#2628 Adding LiveKit
  README.md
Labels: addition

#2625 Added Budibase to Software Development
  README.md
Labels: addition

#2631 Adding NocoDB to Automation
  README.md
Labels: addition

#2633 Add rustypaste to Pastebins
  README.md
Labels: addition

#2636 Re-Add toxcore
  README.md
Labels: addition

#2653 Update plain HTTP and redirected URLs
  README.md
Labels: curation

#2640 Add StoneAge Messenger to Communication - Custom Systems
  README.md
Labels: addition

#2646 Add REI3 to Money, Budgeting & Management
  README.md
Labels: addition, feedback needed

#2651 Add 'exatorrent' to File Transfer
  README.md
Labels: addition

#2663 Removed demo link from Mailu entry
  README.md
Labels: fix

#2655 Add Haven to blogging alternative
  README.md
Labels: addition

#2588 Add Bibliogram to Social Networks
  README.md
Labels: addition

#2660 Add EmuLinkerSF to Games category
  README.md
Labels: addition

#2634 Add "s.Status" to the list.
  README.md
Labels: addition

#2642 Added soketi/pws
  README.md
Labels: addition

#2664 Remove Phabricator (EOL)
  README.md
Labels: curation

#2670 Add UnrealIRCd IRC daemon to Communication - IRC section
  README.md
Labels: addition

#2694 Updated REI3: New public github repo
  README.md
Labels: fix

#2683 Updated description of Passky
  README.md
Labels: fix

#2681 The Bug Genie moved to Pachno
  README.md
Labels: fix

#2698 Remove Hexo
  README.md
Labels: curation
