Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-02, with the labels that each got.

#2347 Add LinkAce to Bookmarks and Link Sharing
  README.md
Labels: addition

#2376 Add Croodle to Polls and Events
  README.md
Labels: addition

#2386 Add Chibisafe to Simgle-click/drag-n-drop upload
  README.md
Labels: addition

#2387 Add dashboard to "Personal Dashboards"
  README.md
Labels: addition

#2389 Add Chatwoot to Custom communication systems
  README.md
Labels: addition

#2415 Fix license tags for olaris/fireshare
  README.md
Labels: fix

#2394 Fix demo site for otranscribe and Ombi
  README.md
Labels: fix

#2392 Add The Battle for Wesnoth to Games
  README.md
Labels: addition

#2399 Adding SeaweedFS to "Object storage/file servers"
  README.md
Labels: addition

#2403 Replace OwnPhotos with LibrePhotos
  README.md
Labels: curation, fix

#2406 Add Web-File-Uploader
  README.md
Labels: addition

#2407 casebox is no longer supported
  README.md
Labels: curation, fix

#2377 Update Send entry
  README.md
Labels: addition

#2395 Add ImageStore to Photo and Video Galleries
  README.md
Labels: addition

#2418 Update Plumi
  README.md
Labels: fix

#2419 Removed confluence from non-free list
  non-free.md
Labels: curation, fix, non-free

#2423 Removing Trigger Happy from free
  README.md
Labels: curation, fix

#2424 Rename Recipes -> Tandoor Recipes
  README.md
Labels: fix

#2417 Add Kleeja
  README.md
Labels: addition

#2420 added MokinToken to list of pastebins
  README.md
Labels: addition

#2416 add xsrv to Self-hosting Solutions
  README.md
Labels: addition

#2425 Add RecipeSage to Recipe management
  README.md
Labels: addition

#2427 Add Solidus to E-commerce
  README.md
Labels: addition

#2429 Update Kimai URL, license, demo, description
  README.md
Labels: fix

#2432 Edit EteSync Server name, source URL
  README.md
Labels: fix

#2408 Adding changedetection.io
  README.md
Labels: addition
