Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-08, with the labels that each got.

#2613 add tracim
  AUTHORS.md
  README.md
Labels: addition, feedback needed

#2618 Added Whoogle to Search Engines section
  README.md
Labels: addition

#2638 sort section contents alphabetically
  README.md
Labels: fix

#2637 remove table of contents, use github's auto-generated TOC
  README.md
Labels: tools

#2577 Add Community-Supported Agriculture (CSA) category with 9 items
  README.md
Labels: addition

#2619 Add Maddy Mail Server to Email/Complete solutions
  README.md
Labels: addition

#2639 Update Standard Notes domain
  README.md
Labels: fix

#2643 Fixing letter 'C' in Retroshare language
  README.md
Labels: fix
