Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-12, with the labels that each got.

#2719 Add Hub20 to Money Management
  README.md
Labels: addition

#2739 Add bookwyrm to non-free, e-books/library section
  non-free.md
Labels: addition, non-free

#2747 Add vaults to Password Managers
  README.md
Labels: addition

#2754 Add OvenMediaEngine to section Video Streaming
  README.md
Labels: addition

#2731 Add "ClearFlask" to "Polls and Events"
  README.md
Labels: addition, non-free, feedback needed

#2767 fix typo
  README.md
Labels: fix

#2764 Update IHateMoney tag
  README.md
Labels: fix

#2751 Add OneDev to Project Management
  README.md
Labels: addition

#2763 OpenMapTiles Server -> MapTiler Server
  non-free.md
Labels: fix, non-free, curation

#2776 use project's correct name
  README.md
Labels: fix

#2752 add schnack
  README.md
Labels: addition, license list

#2787 Removed duplicate table contents
  README.md
Labels: fix

#2782 update information for docker-mailserver
  README.md
Labels: fix

#2774 Adding goshorly to README.md .
  README.md
Labels: addition

#2788 clarify that the default Pull Request description should not be deleted
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tools

#2732 Add Group Office to Groupware
  README.md
Labels: addition

#2797 fix link to "Money, Budgeting & Management"
  README.md
Labels: fix

#2794 Remove Kloudless from non-free as the business no longer offers the software
  non-free.md
Labels: non-free, curation

#2792 Removed crtmpserver (abandoned project)
  README.md
Labels: curation
