Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-06, with the labels that each got.

#2540 Add Libreddit to Social Networks
  README.md
Labels: addition

#2530 Add Nitter to Social Networks
  Makefile
  README.md
Labels: addition

#2557 Removed ReaderSelf entry as UNMAINTAINED
  README.md
Labels: curation

#2558 Remove CharjaBox entry as UNMAINTAINED
  README.md
Labels: curation

#2560 Removed Encode Explorer entry as UNMAINTAINED
  README.md
Labels: curation

#2561 Removed Node Chat entry as UNMAINTAINED
  README.md
Labels: curation

#2562 Removed Subrion entry as UNMAINTAINED
  README.md
Labels: curation

#2563 Removed EdPaper entry as UNMAINTAINED
  README.md
Labels: curation

#2564 Removed ipfs.pics entry as UNMAINTAINED
  README.md
Labels: curation

#2565 Removed DiamanteDesk entry as UNUPDATED
  README.md
Labels: curation

#2566 Removed Tox entry as UNUPDATED
  README.md
Labels: curation

#2567 Removed TinyIssue entry as ARCHIVED
  README.md
Labels: curation

#2584 Demo links should only be used for interactive demos, i.e. not video demonstrations
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: fix, tools

#2585 remove 1backend
  README.md
Labels: curation

#2586 fix/remove broken links
  README.md
Labels: curation, fix

#2583 Fixed Demo Link for EspoCRM
  README.md
Labels: fix

#2591 Renaming Oragono to Ergo
  README.md
Labels: fix

#2593 Update pasty pastebin
  README.md
Labels: fix

#2536 Add OliveTin to Automation category
  README.md
Labels: addition

#2544 Add kcal to CMS - Recipe management
  README.md
Labels: addition

#2545 Add jackal to XMPP Servers
  README.md
Labels: addition

#2547 Add Link to URL Shorteners
  README.md
Labels: addition

#2502 Adds calendso to Booking and Scheduling
  README.md
Labels: addition

#2533 Add Notes'n'Todos to Note-taking and Editors
  README.md
Labels: addition

#2596 update URLs from https://github.com/n1trux/awesome-sysadmin/ -> awesome-foss/awesome-sysadmin
  README.md
Labels: curation, fix
