Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2021-03, with the labels that each got.

#2435 Adding FlashPaper to Pastebins
  README.md
Labels: addition

#2436 Add FileGator to `Web based file managers`
  README.md
Labels: addition

#2433 Add Oblecto as a Media streaming server
  README.md
Labels: addition

#2409 Add Actionsflow to Automation
  README.md
Labels: addition

#2330 add pyShelf to README.md
  README.md
Labels: addition

#2342 Update README.md to add Bitsii Bridge
  README.md
Labels: addition

#2450 Updating Joplin URL
  README.md
Labels: fix

#2454 Remove Cloud Computer
  README.md
Labels: curation, fix

#2464 Remove Volition from Task management/To-do lists - Archived project
  README.md
Labels: curation

#2463 Removed PPnet.
  README.md
Labels: curation

#2444 Add Kerberos.io to Video Streaming
  README.md
Labels: addition

#2438 Added Luke Smith's emailwiz script to the email section.
  README.md
Labels: addition

#2447 Adding Inventree to Money, Budgeting and Management
  README.md
Labels: addition

#2401 Added Mission Kontrol
  README.md
Labels: addition

#2456 Add Kanban Tool to non-feee.md
  non-free.md
Labels: addition, non-free

#2458 Add Cactus Comments
  README.md
Labels: addition

#2445 Add AsmBB to Social
  README.md
Labels: addition

#2466 Update Lemmy URL
  README.md
Labels: fix

#2461 Added EmbassyOS to Self-hosting Solutions
  non-free.md
Labels: addition, non-free

#2472 Remove discontinued Postleaf software
  README.md
Labels: curation
