Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-03, with the labels that each got.

#2892 Demo added for Koel Audio Streaming
  README.md
Labels: fix

#2820 Add Keila to Mailing Lists and Newsletters
  README.md
Labels: addition

#2903 Remove plumi as it's dead
  README.md
Labels: curation

#2890 Demo added for Mealie Recipe Management
  README.md
Labels: fix

#2877 Add Firezone to Misc
  README.md
Labels: addition

#2937 Remove up1 (unmaintained project)
  README.md
Labels: curation

#2866 Add entry for MyPaas to Misc
  README.md
Labels: addition, feedback needed

#2876 Add Koillection to Miscellaneous
  README.md
Labels: addition

#2884 Add Ghostfolio to Money, Budgeting and Management
  README.md
Labels: addition, feedback needed

#2886 Add CloudBeaver to Miscellaneous
  README.md
Labels: addition, feedback needed

#2891 Add groceri.es to the list of 'Recipe Management'
  README.md
Labels: addition

#2938 Remove Bozon (unmaintained project)
  README.md
Labels: curation

#2908 Update to Paperless-ngx instead of -ng
  README.md
Labels: curation

#2901 Update Weaviate (fixed broken link and added docs)
  README.md
Labels: fix

#2894 Removed rss2twtxt - repository and any alternative unavailable.
  README.md
Labels: curation

#2939 Fix typo
  README.md
Labels: fix

#2941 Rename Calendso to Cal.com
  README.md
Labels: fix
