Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-04, with the labels that each got.

#2745 Added Enigma BBS to Communication - Social Networks section
  README.md
Labels: addition, feedback needed

#2827 Add Rapido in CMS list
  README.md
Labels: addition

#2904 Add miniserve - serve files and dirs over HTTP
  README.md
Labels: addition

#2940 Add InvenioRDM to Document Management - Institutional Repository
  README.md
Labels: addition

#2779 Add WorkAdventure to Custom communication systems
  README.md
Labels: addition, feedback needed

#2850 Add Castopod to Blogging Platforms
  README.md
Labels: addition

#2895 Added Livebook to Note-taking & Editors
  README.md
Labels: addition, feedback needed

#2925 Add GarageHQ to Storage
  README.md
Labels: addition

#2929 Adds 'Media Hut' to Photo Galleries section
  README.md
Labels: addition

#2958 Add string.is to Miscellaneous
  README.md
Labels: addition

#2956 Move WorkAdventure to non-free, due to the commons clause
  README.md
  non-free.md
Labels: license list, non-free, feedback needed, discussion, curation

#2971 Remove wrong demo link for diaspora*
  README.md
Labels: fix

#2855 Add Roundup Issue Tracker to the Ticketing section.
  README.md
Labels: addition

#2862 Add Tolgee to Software Development - Localization
  README.md
Labels: addition, feedback needed

#2914 Add Bloben to CalDAV Web-based Clients
  README.md
Labels: addition

#2970 Change ydl_api (deprecated) to ydl_api_ng (new version by the same author)
  README.md
Labels: fix, curation

#2910 Add librengine to Search Engines
  README.md
Labels: addition

#2912 added Drift to Pastebins
  README.md
Labels: addition

#2918 Added WinterCMS to content management systems
  README.md
Labels: addition

#2927 Add ntfy to Communication/Custom
  README.md
Labels: addition

#2935 Add PicoShare to File Transfer section
  README.md
Labels: addition

#2972 Update description and license for Rallly
  README.md
Labels: fix, license list

#2982 Update README.md
  README.md
Labels: fix
