Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-12, with the labels that each got.

#3399 Add Tiledesk to Custom Communication Systems
  README.md
Labels: addition

#3408 Add ITFlow to Ticketing
  README.md
Labels: addition

#3452 Fix wrong header size
  non-free.md
Labels: fix

#3437 Updated broken link for Accelerated Text
  README.md
Labels: fix

#3430 Add Traggo to Time Tracking category
  README.md
Labels: addition

#3461 Add table of contents
  non-free.md
Labels: fix

#3431 Add IconCaptcha
  README.md
Labels: addition

#3435 Add OpenBudgeteer to Money, Budgeting & Management
  README.md
Labels: addition

#3414 Add ustreamer to Media Streaming - Multimedia Streaming
  README.md
Labels: addition

#3439 Add MiroTalk C2C to Communication
  README.md
Labels: addition

#3466 Pull Request template: Any software project you are adding has working installation instructions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feedback needed, enhancement

#3464 Update Postal information and remove outdated links
  README.md
Labels: fix

#3444 Utilitie for managing game servers (PufferPanel).
  README.md
Labels: addition, feedback needed

#3377 POMjs
  README.md
Labels: addition

#3441 Add Hadmean to Software Development - Low Code
  README.md
Labels: addition

#3474 Remove IHateToBudget
  README.md
Labels: curation

#3475 Edit goshorly
  README.md
Labels: fix

#3429 Add Chevereto to free self-hosted software
  README.md
Labels: addition

#3447 Add Akkoma
  README.md
Labels: addition
