Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-07, with the labels that each got.

#2992 Add Bitpoll to Polls and Events
  README.md
Labels: addition

#3020 Added OpenSearch to Search Engines.
  README.md
Labels: addition

#3036 Add wastebin to Pastebin section
  README.md
Labels: addition

#3038 Added Bookmarking -> "Briefkasten"
  README.md
Labels: addition, feedback needed

#3053 Added dashdot to Personal Dashboards
  AUTHORS.md
  README.md
Labels: addition

#3059 Add ZincSearch to search engines
  README.md
Labels: addition

#3086 Remove yclas from eCommerce, source code unavailable
  README.md
Labels: fix, non-free

#2997 Include OpenZiti as a zero trust overlay network
  README.md
Labels: addition

#3021 Add elasticsearch to non-free.md
  non-free.md
Labels: addition, non-free

#3071 Link Clean Up
  README.md
Labels: fix, feedback needed, curation

#3068 Added LinkWarden to Bookmarks and Link Sharing
  README.md
Labels: addition

#2887 Add Dalton Plan to Learning and Courses
  README.md
Labels: addition

#3056 Add LiveStreamDVR (Twitch) to Archiving and Digital Preservation (DP)
  README.md
Labels: addition

#3094 Removed deprecated Myflix, added new cmyflix (same author)
  README.md
Labels: curation

#3115 Remove Goodwork
  README.md
Labels: curation

#3015 Add Sorry Cypress
  README.md
Labels: addition

#3018 Add Uber h3 cells viewer to Maps and Global Positioning System (GPS)
  README.md
Labels: addition

#3099 Added Pydio Demo and Link Cleanup
  README.md
Labels: fix, curation

#3136 remove Boodle
  README.md
Labels: curation

#3137 capitalize all descriptions
  README.md
Labels: fix

#3156 add 'Other' license to the list of licenses
  README.md
Labels: fix, license list

#3147 Add demo for wastebin
  README.md
Labels: enhancement

#3140 Link and README cleanup
  README.md
Labels: curation

#3084 Add Firezone to Gateways
  README.md
Labels: addition

#3085 Added Jump to Personal Dashboards
  README.md
Labels: addition

#3087 Added S-cart to E-commerce
  README.md
Labels: addition

#3092 Added Memos to Note-taking & Editors
  README.md
Labels: addition

#3097 Added Outline Proxy
  README.md
Labels: addition

#3145 Edit checkgithubdates to add archived status
  tests/check-github-commit-dates.py
Labels: tools, enhancement

#3161 habitica: fix license
  README.md
Labels: fix, license list

#3163 fix title case in links to Task management & To-do lists section
  README.md
Labels: fix

#3164 fix title case for Staic Site Generators section link
  README.md
Labels: fix

#3162 Fix license for minio
  README.md
Labels: license list, curation

#3160 Link and README Cleanup
  README.md
  non-free.md
Labels: fix, curation

#3169 remove Other license from license list, unused
  README.md
Labels: fix

#3170 remove tine20
  README.md
Labels: fix, non-free, feedback needed

#3171 Fix licenses for minetest/teeworlds/mapbbcodeshare/ethercalc
  README.md
Labels: fix, license list

#3177 Removed bulletnotes from notes
  README.md
Labels: curation
