Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-10, with the labels that each got.

#3298 addition: Add Gerrit to Project Management
  README.md
Labels: addition, feedback needed

#3306 Add kbin to Social Networking
  README.md
Labels: addition

#3284 Add qpixel to Social Networks and Forum
  README.md
Labels: addition

#3345 Remove dead link
  non-free.md
Labels: fix, curation

#3172 Add Atomic Server to Knowledge Management Tools
  README.md
Labels: addition

#3257 Add Wayback to Archiving and Digital Preservation (DP)
  README.md
Labels: addition

#3299 addition: Add SRS to Miscellaneous
  README.md
Labels: addition

#3312 Add Cgit to Software Development - Project Management
  README.md
Labels: addition

#3316 feat: Add Clink to Url Shorteners
  README.md
Labels: addition

#3301 fixes: Redirect Fixes
  README.md
Labels: fix, feedback needed, curation

#3352 Remove dead link
  README.md
Labels: curation

#3318 feat: Add OhMyForms to Polls and Events
  README.md
Labels: addition

#3314 Add Uploady to Single-clock & Drag-n-drop Upload
  README.md
Labels: addition

#3340 Add Homepage by benphelps to Personal Dashboards
  README.md
Labels: addition

#3370 remove headway
  README.md
Labels: curation

#3334 Add Frigate to Media Streaming - Video Streaming
  README.md
Labels: addition

#3378 remove mkhost
  README.md
Labels: curation
