Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-05, with the labels that each got.

#2949 Add GoSƐ file-uploader
  README.md
Labels: addition

#2964 Add Noisedash to Miscellaneous
  README.md
Labels: addition

#2944 Add Eqivo to Communication - SIP
  README.md
Labels: addition

#2879 Add Wordle to Games
  README.md
Labels: addition

#2800 Add Notifo to custom communication.
  README.md
Labels: addition

#2915 Add time trackers (ActivityWatch, TimeTagger)
  README.md
Labels: addition

#2825 Add Vendure to E-commerce
  README.md
Labels: addition

#2882 Added Uptime Kuma to Status/Uptime Pages
  README.md
Labels: addition

#2906 Added Immich to Photos section
  README.md
Labels: addition

#2917 Add new pastebin "paaster"
  README.md
Labels: addition

#2960 Add Typebot to Communication
  README.md
Labels: addition

#2973 Add Wirow to Communication
  README.md
Labels: addition

#2486 Add Eonza to Automation
  README.md
Labels: addition

#2974 Add LittleLink Custom to Personal Dashboards
  README.md
Labels: addition

#2813 Add Snapdrop to File Transfer - Single-click & Drag-n-drop Upload
  README.md
Labels: addition

#2975 Adding Gray Duck Mail to Communication - Email...
  README.md
Labels: addition

#3013 move october CMS to non-free.md
  README.md
  non-free.md
Labels: fix, non-free, curation

#3010 Update to Karaoke Eternal (formerly Karaoke Forever)
  README.md
Labels: fix

#3016 Remove Dead Demo Links
  README.md
Labels: fix, curation

#2843 Add Word-Mastermind to Games
  README.md
Labels: addition

#2909 added Fenrus to dashboard section
  README.md
Labels: addition

#2951 Abb Bubo Reader to Feed Readers
  README.md
Labels: addition

#2986 Add Bicimon to Maps and Global Positioning System
  README.md
Labels: addition

#3034 Remove pste from File Transfer section
  README.md
Labels: curation

#3022 Formatting and Link Cleanup
  README.md
  non-free.md
Labels: fix, curation

#3027 Update information on Bolt CMS
  README.md
Labels: fix, curation
