Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-09, with the labels that each got.

#3149 Adds WeTTY to Gateways and Terminal Sharing
  README.md
Labels: addition

#3185 Add hastypaste to pastebin
  README.md
Labels: addition

#3202 Add Ganymede to Archiving and Digital Preservation
  README.md
Labels: addition

#3213 Added Fess to Search Engines
  README.md
Labels: addition

#3216 added ioBroker to IoT
  README.md
Labels: addition

#3182 Rearranged Tania's links and added FarmOs demo link
  README.md
Labels: enhancement

#3263 Update demo link for Bloben
  README.md
Labels: fix

#3228 Non Free clean up
  non-free.md
Labels: fix, non-free, curation

#3243 Readme cleanup
  README.md
Labels: fix, curation

#3266 Update OrangeHRM demo, source links
  README.md
Labels: fix, curation

#3268 Remove empty sections
  README.md
Labels: fix

#3269 add Vigil to Status / Uptime pages
  README.md
Labels: fix, addition, feedback needed, curation

#3244 Add Tipi to Self-hosting Solutions
  README.md
Labels: addition

#3278 remove Photato
  README.md
Labels: fix, curation

#3274 Redirect fixes and General Project Clean Up
  README.md
Labels: fix, curation

#3254 Add MiroTalk to Communication
  README.md
Labels: addition

#2840 Add CasaOS
  README.md
Labels: addition

#3109 Added Nhost to FaaS & Serverless
  README.md
Labels: addition

#3253 Add Umbrel to non-free.md
  non-free.md
Labels: addition, non-free

#3259 Add OurShoppingList to the Task Management & To-do Lists section
  README.md
Labels: addition

#3220 Add Short{Paste}
  README.md
Labels: addition

#3238 Add EMQX to Internet of Things
  README.md
Labels: addition

#3224 Add neonlink to Bookmarks and Link Sharing
  README.md
Labels: addition

#3234 Add Recepturer to Recipe Management
  README.md
Labels: addition

#2978 Add Medusa to E-commerce
  README.md
Labels: addition

#3210 Add Vivum to selfhosting solutions
  README.md
Labels: addition

#3007 Add SnyPy to Pastebins
  README.md
Labels: addition, feedback needed

#3258 Add reciphpes! software to the Recipe Management section
  README.md
Labels: addition

#3240 Adds Software Development - Low Code Section
  README.md
Labels: curation, enhancement

#3288 Cleanup Bookmark section
  README.md
Labels: fix, feedback needed, curation

#3294 Fix back to top links and Typo
  README.md
Labels: fix, enhancement

#3271 Add Christmas Community to Polls and Events
  README.md
Labels: addition

#3272 Add Picaport to nonfree photos and videos
  non-free.md
Labels: addition, non-free

#2789 Add Wiznote to non-free Knowledge Management Tools
  non-free.md
Labels: addition, non-free

#3239 Add meshcentral
  README.md
Labels: addition

#3035 Add the Headway project to Maps/GPS
  README.md
Labels: addition

#3280 Add Claper to Polls and Events
  README.md
Labels: addition

#3265 Add Payload to CMS
  README.md
Labels: addition

#3281 added FlatPress to Blogging Platforms
  README.md
Labels: addition

#3307 Add Stalwart JMAP server to Communication - Email - Mail Delivery Agents
  README.md
Labels: addition

#3289 Add Iguana to Ticketing
  README.md
Labels: addition

#3302 fixes: General Cleanup
  README.md
Labels: fix, curation

#2749 Add Marauder to Self-hosting Solutions
  README.md
Labels: addition, feedback needed

#3293 Add Svix to Software Development - API Management
  README.md
Labels: addition

#3300 Add Tubesync to Automation
  README.md
Labels: addition

#3286 Add Maloja to Media Streaming - Audio Streaming
  README.md
Labels: addition

#3305 Add Easypanel
  non-free.md
Labels: addition, non-free

#3308 Add KitchenOwl to Recipe Management
  README.md
Labels: addition
