Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-06, with the labels that each got.

#3042 Link Cleanup and Formatting
  README.md
Labels: fix, curation

#3037 Removing Sit from Ticketing
  README.md
Labels: curation

#2945 Adding Kodi, Octave Online, Pterodactyl
  README.md
Labels: addition, feedback needed

#3046 move sentry to non-free.md, update license and name
  non-free.md
Labels: fix, non-free

#3043 Further link clean up
  README.md
Labels: curation

#2857 Add ARRCON to Games
  README.md
Labels: addition, discussion, curation

#2983 Add Mars Server to Self Hosting
  README.md
Labels: addition

#2999 Add pastila.nl
  README.md
Labels: addition

#3039 Added Personal Dashboards -> "Newtelco Tab"
  README.md
Labels: addition

#3040 Add MicroBin to Pastebins
  README.md
Labels: addition

#3041 Added Stump to Document Management - E-books
  README.md
Labels: addition

#2990 Adding Datasette.io
  README.md
Labels: addition

#3003 Added Solr to Misc/Other.
  README.md
Labels: addition

#3048 Add a page navigation link for the `Games - Administrative Utilities & Control Panels` category
  README.md
Labels: fix

#3063 Fix actionsflow link
  README.md
Labels: fix

#3051 Added GitHub link for wiki.js
  README.md
Labels: fix, curation
