Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-02, with the labels that each got.

#2861 move n8n to non-free.md
  README.md
  non-free.md
Labels: fix, non-free

#2842 Add Vocascan to Learning and Courses
  README.md
Labels: addition

#2814 Add SnappyMail to Communication - Email - Webmail Clients
  README.md
Labels: addition

#2830 Improves self-hosting definition README.md
  README.md
Labels: curation

#2851 Added SimpleX Chat to Custom Communication Systems
  README.md
Labels: addition

#2880 Fix: Link to source for Neos CMS
  README.md
Labels: fix

#2863 Remove drive virtual, domain no longer exist
  non-free.md
Labels: non-free, curation
