Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-11, with the labels that each got.

#3384 Remove PhotoLight
  README.md
Labels: curation

#3366 Add Gatus to Status / Uptime pages
  README.md
Labels: addition

#3383 Remove Chevereto from free self-hosted software
  README.md
Labels: curation

#3389 Updated Databag Entry in Custom Communication.
  README.md
Labels: enhancement

#3380 Fix license for FoodCoopShop
  README.md
Labels: fix

#3333 Added Rustdesk to Remote Access
  README.md
Labels: addition

#3339 Add Dendrite to Custom Communication Systems
  README.md
Labels: addition, feedback needed

#3362 Re-Add tine20
  README.md
Labels: addition

#3394 remove Pizzly (the project is archived)
  README.md
Labels: curation

#3313 Add sourcehut to Software Development - Project Management
  README.md
Labels: addition, feedback needed

#3381 Add Password Pusher to Pastebins
  README.md
Labels: addition, feedback needed

#3385 Add Chirpy comment sysytem
  README.md
Labels: addition

#3403 remove linx-server
  README.md
Labels: fix, curation

#3348 Add coolify to section serverless
  README.md
Labels: addition

#3424 DokuWiki: add missing word to description
  README.md
Labels: fix

#3425 Move WriteFreely to Blogging-Platforms
  README.md
Labels: fix

#3427 Remove Plume. Not actively maintained.
  README.md
Labels: curation

#3421 Update Openspeedtest license
  README.md
  non-free.md
Labels: curation

#3396 Add Yopass
  README.md
Labels: addition

#3401 Add Bsimp to Audio Streaming
  README.md
Labels: addition

#3410 Add docassemble to Booking and Scheduling
  README.md
Labels: addition
