Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-08, with the labels that each got.

#3076 Add plugNmeet to Communication - Custom Communication Systems
  README.md
Labels: addition

#3078 Add BitcartCC to Money, Budgeting & Management section
  README.md
Labels: addition

#3079 Add Touca to Software Development - Testing
  README.md
Labels: addition

#3073 Add DePay (Web3 Payments) to Money, Budgeting & Management
  README.md
Labels: addition

#3152 Add `vSMTP` to `Communication - Email - Mail Transfer Agents`
  README.md
Labels: addition

#3112 Added Novu
  README.md
Labels: addition

#3111 Add Instiki to Wikis
  README.md
Labels: addition

#3067 Add GoToSocial to Communication
  README.md
Labels: addition

#2873 Add Agora-Project to Groupware
  README.md
Labels: addition

#3120 Add NATS in Miscellaneous category
  README.md
Labels: addition

#3142 Added Kiwix to wikis
  README.md
Labels: addition

#3128 Added OpenSpeedTest to Miscellaneous
  non-free.md
Labels: addition, license list, non-free

#3183 Dead Projects Removal
  README.md
Labels: fix, feedback needed, curation

#3123 Added LibreTranslate to Misc
  README.md
Labels: addition

#3176 Updated demo links for Tandoor and Mealie
  README.md
Labels: fix, enhancement

#3188 Update plugNmeet to Communication - Video Conferencing
  README.md
Labels: fix

#3143 fix: add back code-server, fix Coder
  README.md
Labels: fix, addition

#3190 Issue closing and readme cleanup
  README.md
Labels: fix, curation

#3199 Moved depay.fi -> depay.com
  README.md
Labels: fix

#3203 non-free.md: fix language tags
  non-free.md
Labels: fix, non-free

#3204 remove documize from non-free.md
  non-free.md
Labels: fix, curation

#3206 non-free.md: remove Analytics section/move items to awesome-analytics
  non-free.md
Labels: fix, curation

#3122 Added Yarr to Feed Readers
  README.md
Labels: addition

#3121 Added Peppermint to Ticketing
  README.md
Labels: addition

#3126 Added Thumbor to Photo and Video Galleries
  README.md
Labels: addition

#3103 Add `this week in past` to `Photo and Video Galleries`
  README.md
Labels: addition

#3196 Added openSIPS entry to Communications/SIPS
  README.md
Labels: addition

#3186 Add Statusping.ng to Status pages
  README.md
Labels: addition

#3193 Added Minimalist Online Markdown Editor to Note Taking Editors
  README.md
Labels: addition

#3139 Added Buku to Bookmarks
  README.md
Labels: addition

#3127 Added DOMJudge to Misc
  README.md
Labels: addition, feedback needed

#3165 Add Manticore Search to Search Engines
  README.md
Labels: addition

#3155 Add Traq
  README.md
Labels: addition

#3102 Add IndiCom to Communication - Custom Communication System
  README.md
Labels: addition

#3195 Add Discord Bot Dashboard
  README.md
Labels: addition

#3158 Add Bytebase to Miscellaneous
  README.md
Labels: addition

#3192 Added Section Descriptions Part 2
  README.md
Labels: feedback needed, enhancement

#3194 Added Omeka-S to Digital Archiving
  README.md
Labels: addition

#3197 README and Stale Issue Cleanup
  README.md
Labels: fix, curation

#3218 Maps and Global Positioning System: add link to awesome-openstreetmap
  README.md
Labels: enhancement

#3215 Descriptions Part 3
  README.md
Labels: fix, help wanted, enhancement

#3211 Relocated Taiga source link.
  README.md
Labels: fix

#3179 Update to firefox sync server url
  README.md
Labels: fix, addition, feedback needed, help wanted, curation

#3221 Cleanup of Gateway Section
  README.md
Labels: fix, curation

#3223 Nonfree Redirect Fixes Part 1
  non-free.md
Labels: fix, non-free, curation

#3227 Non-free redirect fixes part 2
  non-free.md
Labels: fix, non-free

#3222 Redirect fixes Part 1
  README.md
Labels: fix, curation

#3214 add mkhost to Communication - Email - Complete Solutions
  README.md
Labels: addition

#3226 Add Overseerr to Misc
  README.md
Labels: addition
