Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2022-01, with the labels that each got.

#2821 Update License of ydl_api as per Totonyus/ydl_api#6
  README.md
Labels: fix, license list

#2802 Remove Airsonic
  README.md
Labels: curation

#2812 Remove ZeroQueue - it's been archived
  README.md
Labels: curation

#2717 Add Status section + remove cachet
  README.md
Labels: fix, addition, curation

#2833 Update README.md
  README.md
Labels: fix

#2828 update twtxt.net/yarn.social url
  README.md
Labels: fix

#2839 Remove outdated Tube URL
  README.md
Labels: fix

#2724 Add screensy to Communication - Custom Communication Systems
  README.md
Labels: addition

#2796 Add OTOBO to Ticketing
  README.md
Labels: addition

#2798 Add Dim to Media Streaming
  README.md
Labels: addition

#2844 JARR demo instance moved
  README.md
Labels: fix

#2777 Add Peergos to File Transfer & Synchronization
  README.md
Labels: addition, feedback needed

#2853 Add Grist to Office Suites
  README.md
Labels: addition

#2838 Add wantguns/bin under Pastebins
  AUTHORS.md
  README.md
Labels: addition

#2823 Added MetaTube to Automation section
  README.md
Labels: addition

#2816 Add SIP Irrigation control to IoT
  README.md
Labels: addition

#2835 Add Supysonic to Audio streaming section
  README.md
Labels: addition
