Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-04, with the labels that each got.

#3643 Add Actual to Money, Budgeting & Management
  README.md
Labels: addition

#3645 Added Seatsurfing desk booking
  README.md
Labels: addition

#3680 remove socks5engine (unmaintained since 2019, website down)
  README.md
Labels: curation

#3693 Fix: Update Audiobookshelf clients
  README.md
Labels: fix

#3697 remove HospitalRun (the project is archived)
  README.md
Labels: curation

#3698 remove Tuber (the project is archived)
  README.md
Labels: curation

#3710 update Drupal Commerce source code link
  README.md
Labels: fix

#3700 remove MissionKontrol (unmaintained since 2021)
  README.md
Labels: curation

#3702 remove Bootcamp (unmaintained since April 2020)
  README.md
Labels: curation

#3703 remove Isotope Mail (unmaintained since 2019)
  README.md
Labels: curation

#3705 remove pump.io (unmaintained since april 2022)
  README.md
Labels: curation

#3706 remove koozic (unmaintained since 2020)
  README.md
Labels: curation

#3707 remove Snibox (unmaintained since 2019)
  README.md
Labels: curation

#3708 remove microgit (unmaintained since 2020)
  README.md
Labels: curation

#3709 remove dyu comments (unmaintained since 2019)
  README.md
Labels: curation

#3679 Add Easyshortener to URL Shorteners catagory
  README.md
Labels: addition

#3689 Add swingmusic to media streaming
  README.md
Labels: addition

#3690 Add Shifter
  README.md
Labels: addition

#3696 Add EasyWI to Games - Admin Utilities & Control Panels
  README.md
Labels: addition

#3728 Update Tipi website, demo and source code urls
  README.md
Labels: fix, enhancement

#3722 remove Thingspeak (unmaintained since 2015)
  README.md
Labels: curation

#3723 remove ympd (unmaintained since 2018)
  README.md
Labels: curation

#3724 remove Moonmoon (unmaintained since 2018)
  README.md
Labels: curation

#3726 remove Bumpy Booby (unmaintained since 2016)
  README.md
Labels: curation

#3738 remove gigablast website link (website gone, connection refused)
  README.md
Labels: fix, curation

#3711 Add Fathom Analytics
  README.md
Labels: addition

#3736 remove JD Esurvey (unmaintained since 2021)
  README.md
Labels: curation

#3737 remove Helpy (unmaintained since 2021)
  README.md
Labels: curation

#3742 remove Shaark (unmaintained since 2020)
  README.md
Labels: curation

#3743 remove Groove Basin (unmaintained since 2021)
  README.md
Labels: curation

#3744 remove EpochTalk (unmaintained since 2021)
  README.md
Labels: curation

#3747 remove s3server (unmaintained since 2020)
  README.md
Labels: curation

#3748 remove updog (unmaintained since 2020)
  README.md
Labels: curation

#3749 remove WebODF (unmaintained since 2020)
  README.md
Labels: curation

#3764 remove AllTube (the project is archived)
  README.md
Labels: curation
