Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-06, with the labels that each got.

#3858 Simplify GPL-X licenses
  README.md
Labels: license list, curation, enhancement

#3792 Add OctoBot to Money, Budgeting & Management
  README.md
Labels: addition

#3801 add vod2pod-rss to Media Streaming - Audio Streaming section
  README.md
Labels: addition

#3866 Fix type on Aptabase url
  README.md
Labels: fix

#3870 Fix papermerge url
  README.md
Labels: fix

#3837 remove Clink (unmaintained since 2021, certificate expired)
  README.md
Labels: curation

#3852 Add penpot to Miscellaneous
  README.md
Labels: addition

#3851 Add Kill Bill to Money, Budgeting & Management
  README.md
Labels: addition

#3762 Add Lynx to URL Shorteners
  README.md
Labels: addition

#3874 Fix Nextcloud Memories
  README.md
Labels: fix

#3875 Fix pastefy url
  README.md
Labels: fix

#3877 BitcartCC: renaming to Bitcart, update domains
  README.md
Labels: fix

#3872 Remove Demo from Redmine
  README.md
Labels: curation

#3884 Remove Cagette from Community-Supported Agriculture
  README.md
Labels: fix, curation

#3778 Add SolidInvoice to Money, Budgeting & Management
  README.md
Labels: addition

#3752 Add envlinks to Personal dashboards
  README.md
Labels: addition

#3861 Add AmuseWiki to Wikis
  README.md
Labels: addition

#3850 Add Cosmos to Non-free
  non-free.md
Labels: addition, non-free

#3865 Add Jellyseerr to Miscellaneous
  README.md
Labels: addition

#3871 Remove Orchest from Miscellaneous (officially unmaintained, website down)
  README.md
Labels: curation

#3888 Remove Demo from Activepieces
  README.md
Labels: fix

#3729 Added Just Short It to URL Shorteners
  README.md
Labels: addition

#3641 Add theme.park
  README.md
Labels: addition, discussion

#3892 Fix typography in awesome-sysadmin url
  README.md
Labels: fix

#3897 Update LiveKit Demo URL
  README.md
Labels: fix

#3849 Add PoeticMetric to Analytics
  README.md
Labels: addition

#3847 Add Flagsmith to Miscellaneous section
  README.md
Labels: addition

#3882 Add Limbas to Database Management
  README.md
Labels: addition

#3885 Add SyncMarks Bookmarks and Link Sharing
  README.md
Labels: addition

#3886 Add YoutubeDLServer to Automation
  README.md
Labels: addition

#3891 Add pacebin to Pastebins
  README.md
Labels: addition

#3887 Add Romm to Games
  README.md
Labels: addition

#3905 Remove Tasks from Task Management & To-do Lists
  README.md
Labels: curation

#3908 Remove BicBucStriim from Document Management - E-books
  README.md
Labels: curation

#3909 Remove Bonobo Git Server from Software Development - Project Management
  README.md
Labels: curation

#3912 Remove Marauder (the project has been archived)
  README.md
Labels: curation

#3896 Remove Vocascan (unmaintained since June 2022, website down/self-signed cert)
  README.md
Labels: curation

#3878 Add Tailchat to Communication - Custom Communication Systems
  README.md
Labels: addition

#3822 Added Manage My Damn Life to section Calendar & Contacts - CalDAV or …
  README.md
Labels: addition, discussion

#3903 mark Automation and Continuous Integration sections as related
  README.md
Labels: enhancement

#3857 Add Bigcapital self-hosted software
  README.md
Labels: addition

#3901 Add Apache Airflow to Automation
  README.md
Labels: addition

#3915 Remove Mealie demo link (too many redirects)
  README.md
Labels: fix

#3731 Add Mere Medical to Miscellaneous section
  README.md
Labels: addition

#3919 Remove ethercalc (unmaintained since 2020)
  README.md
Labels: curation

#3918 Fix SourceBans++ URL
  README.md
Labels: fix

#3904 Add Lodestone to Games - Administrative Utilities & Control Panels
  README.md
Labels: addition

#3902 Add Kubek to Games - Administrative Utilities & Control Panels
  README.md
Labels: addition

#3914 external links: add links to more communities/forums
  README.md
Labels: enhancement

#3927 Remove Croodle (unmaintained since 2021)
  README.md
Labels: curation

#3933 Removed the Valoren source-code linkto the github page, Add link to Valoren source-code to the gitlab page
  README.md
Labels: fix

#3938 Remove CoreDNS (already listed at awesome-sysadmin)
  README.md
Labels: fix, curation

#3939 DNS: fix links to awesome-sysadmin
  README.md
Labels: fix

#3940 DNS: move nsupdate.info/SPF toolbox to awesome-sysadmin/DNS - Control Panels & Domain Management
  README.md
Labels: curation

#3941 DNS: clarify that the section is about DNS-based ad blockers
  README.md
Labels: curation, enhancement

#3942 DNS: move Pi-Hole from awesome-sysadmin/DNS Control Panels & Domain Management
  README.md
Labels: addition, curation

#3922 Remove twister (unmaintained since 2022)
  README.md
Labels: curation

#3923 Remove Photonix (unmaintained since 2022)
  README.md
Labels: curation

#3570 remove 0bin (unmaintained since 2021)
  README.md
Labels: curation

#3916 Add Kubero to Software Development section
  README.md
Labels: addition
