Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-01, with the labels that each got.

#3478 Add Photoprism Demo url
  README.md
Labels: enhancement

#3463 Add F-Droid to Miscellanous
  README.md
Labels: addition

#3451 Add Automatisch to automation section
  README.md
Labels: addition

#3118 Add Apprise to Communication - Custom Communication Systems Section
  README.md
Labels: addition

#3357 Added wiki software PukiWiki to Section Wiki
  README.md
Labels: addition

#3369 Add Benotes to Note-taking
  README.md
Labels: addition, feedback needed

#3446 Add Retrospring to Communication - Social Networks and Forums
  README.md
Labels: addition

#3462 Add Unraid
  non-free.md
Labels: addition, non-free

#3476 Add Cloudlog to Miscellaneous
  README.md
Labels: addition

#3492 Add Veloren to Games
  README.md
Labels: addition

#3493 Add 0 A.D. to Games
  README.md
Labels: addition

#3507 remove moinmoin
  README.md
Labels: curation

#3506 remove jingo
  README.md
Labels: curation

#3501 remove DecSync CC (not-self-hosted)
  README.md
Labels: fix, feedback needed, curation

#3514 Fix license for Planka
  README.md
Labels: fix

#3521 Update Wiki.js website link
  README.md
Labels: fix

#3526 PhotoPrism changed license to GPL-3.0
  README.md
Labels: fix

#3465 Add Bar Assistant to recipe management
  README.md
Labels: addition

#3503 Added Activepieces to Automation
  README.md
Labels: addition

#3518 remove Babelfish (unmaintained)
  README.md
Labels: curation

#3519 remove Cartulary (unmaintained)
  README.md
Labels: curation

#3520 remove Ironfunctions (unmaintained)
  README.md
Labels: curation

#3517 remove Abilian SBE (unmaintained)
  README.md
Labels: curation

#3516 remove 411 (unmaintained)
  README.md
Labels: curation

#3509 Add smartdns to DNS section
  README.md
Labels: addition

#3374 Add Yaade to API management
  README.md
Labels: addition

#3533 OCS was discontinued (add an advice or remove)
  README.md
Labels: curation

#3542 remove dead links, unmaintained projects
  README.md
  non-free.md
Labels: curation

#3544 update web address for paperless-ngx
  README.md
Labels: fix

#3545 Remove dead links, unmaintained projects
  README.md
Labels: curation

#3487 Adding Picsur to Archiving and Digital Preservation
  README.md
Labels: addition

#3546 Cleanup dead links
  README.md
Labels: curation

#3547 Update licenses, cleanup/simplify license list, remove unmaintained projects
  README.md
  non-free.md
Labels: license list, non-free, curation, enhancement

#3548 Cleanup dead links
  README.md
Labels: curation

#3471 Add Takahē to Social Networking and Forum software
  README.md
Labels: addition

#3555 tools: remove obsolete test tooling + add CI badge
  .github/CONTRIBUTING.md
  .travis.yml
  Makefile
  README.md
  tests/Dangerfile
  tests/check-github-commit-dates.py
  tests/test.js
Labels: tools, curation
