Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-07, with the labels that each got.

#3965 Update README.md links for Gnu Social entry
  README.md
Labels: fix

#3928 Remove todoMini (unmaintained since 2022, website down)
  README.md
Labels: curation

#3948 Remove myDrive (unmaintained since 2021)
  README.md
Labels: curation

#3950 Remove Enigma Reloaded (unmaintained since 2021)
  README.md
Labels: curation

#3951 Remove PHP-Proxy (unmaintained since 2020)
  README.md
Labels: curation

#3952 Remove Paste (unmaintained since 2021)
  README.md
Labels: curation

#3953 Remove Excision Mail (unmaintained since June 2022)
  README.md
Labels: curation

#3945 Update language tags
  README.md
Labels: enhancement

#3970 Remove Tiny Tiny IRC (project archived, repo down)
  README.md
Labels: curation

#3921 Add Swetrix to Analytics
  README.md
Labels: addition

#3773 Add httprd to Remote Access
  README.md
Labels: addition

#3827 Add Koblas to proxy category
  README.md
Labels: addition, feedback needed, reviewers wanted

#3931 Add GO Feature Flag to Miscellaneous
  README.md
Labels: addition

#3898 Added YABin to pastebins
  AUTHORS.md
  README.md
Labels: addition, feedback needed, reviewers wanted

#3977 update 92five license
  non-free.md
Labels: license list, non-free, curation

#3984 Move VanDAM to Miscellaneous
  README.md
Labels: fix

#3988 Pull Request template: fix name of Miscellaneous section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix

#3989 CONTRIBUTING.md: approved Pull Requests are usually merged one week after approval
  .github/CONTRIBUTING.md
Labels: enhancement

#3992 Add source code link for asterisk
  README.md
Labels: fix

#3993 Fix alphabetical ordering, duplicate links
  README.md
Labels: fix

#3964 Add Adminer to Database Management
  README.md
Labels: addition, reviewers wanted

#3862 Add Mixpost to Analytics
  README.md
Labels: addition

#3895 Add HyperSwitch to Payment Processors
  README.md
Labels: addition

#3999 Pull Request template: Any software project you are adding was first released more than 4 months ago
  .github/PULL_REQUEST_TEMPLATE.md
Labels: curation, enhancement

#3980 Remove Tokumei (unmaintained since 2017)
  README.md
Labels: curation

#3505 remove cowyo (unmaintained since 2020)
  README.md
Labels: curation

#3562 remove ML Workspace (unmaintained since 2021)
  README.md
Labels: curation

#3981 Remove GetSimple CMS (unmaintained since 2022)
  README.md
Labels: curation

#4001 Remove StockazNG (dead link)
  README.md
Labels: curation

#4003 update URLs of github repositories/follow redirects
  README.md
Labels: fix, curation, enhancement

#4002 fix: Freenet have changed to Hyphanet
  README.md
Labels: fix

#3990 External links: condense/reorder links
  README.md
Labels: enhancement

#3947 add adguard to dns section
  README.md
Labels: addition

#3958 Add LittleLink to Personal Dashboards
  README.md
Labels: addition

#3935 Add FlowForge in IoT category
  README.md
Labels: addition

#3975 Add Keygen to Misc
  non-free.md
Labels: addition, non-free

#4007 Fixed small typo qdvertisements->advertisements
  README.md
Labels: fix

#3976 Update language tags - Part 2
  README.md
Labels: enhancement

#3998 Pull Request template: require forks to provide a list of differences with the original project
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, reviewers wanted

#4018 tools/authors: use plaintext instead of markdown for the authors file
  AUTHORS
  AUTHORS.md
  Makefile
  README.md
Labels: tools, enhancement

#4017 Fix activepieces source code URL
  README.md
Labels: fix

#4019 header/footer: use absolute links, don't hotlink awesome badge
  README.md
  _static/awesome.png
Labels: fix, enhancement

#4010 Remove Coolify demo link (timeout)
  README.md
Labels: fix, curation

#4012 Remove Erxes demo link (HTTP 502), update language/platform
  README.md
Labels: fix, curation

#4015 Remove Tipi demo link (timeout)
  README.md
Labels: fix, curation

#4020 deduplicate chevereto entry across README.md/non-free.md
  README.md
  non-free.md
Labels: fix

#4021 shorten/fix aptabase description
  README.md
Labels: fix

#4022 fix alphabetical ordering, trailing/whitespace, 'related'/'please visit' ordering
  README.md
Labels: fix

#4025 update source code URLs following github redirects
  README.md
  non-free.md
Labels: curation

#4013 Remove PukiWiki (source code unreachable)
  README.md
Labels: fix, curation

#4016 Remove Uguu homepage link (connection refused)
  README.md
Labels: fix, curation

#4029 Fix source code for dovel.email
  README.md
Labels: fix

#3929 Add Sendy to (non-free) Communication - Email - Mailing Lists and Newsletters
  non-free.md
Labels: addition, non-free

#3987 Add CraftyControl to Games - Administrative Utilities & Control Panels
  README.md
Labels: addition

#4042 Fix Nominatim description
  README.md
Labels: fix

#4044 Update CI/daily dead links/unmaintained projects checks badge
  README.md
Labels: fix

#3978 Add yt-dlp Web UI to Automation
  README.md
Labels: addition

#3967 Add Open-Meteo to Miscellaneous
  README.md
Labels: addition

#3994 Add Kasm to Miscellaneous
  README.md
Labels: addition

#4036 Remove Demo link for SearX
  README.md
Labels: fix

#4024 external links: reorder communities/forums
  README.md
Labels: enhancement

#3954 Add atsumeru to Document Management - E-books README.md
  README.md
Labels: addition, reviewers wanted

#3971 Add SQLPage to Software Development - Low Code
  README.md
Labels: addition, feedback needed, reviewers wanted

#4035 Add SearXNG to Search Engines
  README.md
Labels: addition

#4040 Remove xBrowserSync (unmaintained since 2021/2022)
  README.md
Labels: curation

#4041 Remove Share (unmaintained since May 2022)
  README.md
Labels: curation

#4066 update CI badges
  README.md
Labels: fix, tools

#4067 fix: Typos and Dead Link
  README.md
Labels: fix, curation

#4045 Remove schnack (unmaintained since June 2022)
  README.md
Labels: curation

#4046 Remove Hauk (unmaintained since March 2021)
  README.md
Labels: curation

#4047 Remove DailyNotes (unmaintained since Feb 2022)
  README.md
Labels: curation
