Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-05, with the labels that each got.

#3765 remove socksbin (unmaintained since March, 2022)
  README.md
Labels: curation

#3766 remove snipt (unmaintained since 2021)
  README.md
Labels: curation

#3767 remove sovereign (unmaintained since 2021)
  README.md
Labels: curation

#3768 remove pagekit (unmaintained since 2020)
  README.md
Labels: curation

#3769 remove mopidy musicbox (unmaintained since 2020)
  README.md
Labels: curation

#3770 remove microproxy (unmaintained since Jan, 2022)
  README.md
Labels: curation

#3772 remove chibisafe (unmaintained since Jan, 2022)
  README.md
Labels: curation

#3782 Remove OpenNote.
  README.md
Labels: curation

#3785 update JupyterLab homepage URL
  README.md
Labels: fix

#3681 Add stirling-pdf to Document management
  README.md
Labels: addition

#3797 Update Screensy demo link
  README.md
Labels: fix

#3804 Updated Databag Description: Custom Cummunications
  README.md
Labels: enhancement

#3783 remove ZeroNet (unmaintained since 2021)
  README.md
Labels: curation

#3784 remove PHPBack (unmaintained since 2021)
  README.md
Labels: curation

#3787 Remove Newtelco Tab (unmaintained since August 2022, vulnerabilities, website down)
  README.md
Labels: curation

#3790 Create Inventory Management section
  README.md
Labels: curation

#3796 remove LibreNews (unmaintained since 2021, website down)
  README.md
Labels: curation

#3811 Pull Request template: additions should not already be listed at dbdb.io
  .github/PULL_REQUEST_TEMPLATE.md
Labels: curation, enhancement

#3617 Custom Communication Systems: Added OTS-share
  README.md
Labels: addition

#3714 Add Opengist to Pastebins
  README.md
Labels: addition

#3732 Added RPort
  README.md
Labels: addition

#3735 Add Plane to Software Development - Project Management
  README.md
Labels: addition

#3741 Add Evidence to Analytics Section
  README.md
Labels: addition

#3806 Remove Screaming Liquid Tiger (website down)
  README.md
Labels: curation

#3808 Remove Tabby (unmaintained since January 2022)
  README.md
Labels: curation

#3809 Remove Taskboard (unmaintained since 2021)
  README.md
Labels: curation

#3819 remove EasyQuickImport (unmaintained since 2021, website down)
  README.md
Labels: curation

#3831 project management: remove link to awesome-sysadmin
  README.md
Labels: fix, curation

#3840 Update outdated CryptPad URLs
  README.md
Labels: fix

#3817 Added Mycorrhiza Wiki to Wikis section
  README.md
Labels: addition

#3820 Added flatnotes to Note-taking & Editors
  README.md
Labels: addition

#3810 Add Tasks.md
  README.md
Labels: addition

#3776 Add Homarr
  README.md
Labels: addition

#3746 Added Starbase 80 to personal dashboards
  README.md
Labels: addition

#3835 Added Upsnap to Status / Uptime pages
  README.md
Labels: addition

#3618 Analytics: Add Netron
  README.md
Labels: addition

#3839 Remove Flame (unmaintained since 2022) from Personal Dashboards
  README.md
Labels: curation

#3842 Remove Dispatch (unmaintained since 2022, Website down) from Communication - IRC
  README.md
Labels: curation

#3845 Remove OpenSupport (unmaintained since 2022, website broken) from Ticketing
  README.md
Labels: curation
