Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-08, with the labels that each got.

#4053 Added FOSSBilling to Money, Budgeting & Management
  README.md
Labels: addition

#4052 Add Remotely to Remote Access
  README.md
Labels: addition

#4056 Add Screego to Custom Communication Systems
  README.md
Labels: addition

#4061 Remove shorturl (unmaintained since 2021, website down)
  README.md
Labels: fix, curation

#4062 Remove golinks (unmaintained since June 2022)
  README.md
Labels: curation

#4063 Remove prologic pastebin (unmaintained since 2021)
  README.md
Labels: curation

#4064 Remove todo (unmaintained since November 2022, outdated base image)
  README.md
Labels: curation

#4065 Remove wiki (unmaintained since 2021)
  README.md
Labels: curation

#4072 Move Baby Buddy, Habitica and wger to Miscellaneous
  README.md
Labels: curation

#4028 Add Loggit to Miscellaneous
  README.md
Labels: addition

#4068 Add OpenRouteService to Maps and Global Positioning System (GPS)
  README.md
Labels: addition

#4082 Remove Tanoshi (the project is archived)
  README.md
Labels: fix, curation

#4099 Fix mealie URLs
  README.md
Labels: fix

#4111 Fix LinkWarden
  README.md
Labels: fix

#4117 Change link to Kubek
  README.md
Labels: fix

#4091 Remove Anchor from non-free.md since it seems to be a dead project
  non-free.md
Labels: curation

#3868 Add DaneeCloud to File Transfer - Object Storage & File Servers
  non-free.md
Labels: addition, non-free

#4123 Standardize "alternative to" proprietary services formatting
  README.md
Labels: enhancement

#4083 move issue tracking/contribution workflows/project management to awesome-selfhosted-data
  .github/.mailmap
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_template.md
  Makefile
  README.md
Labels: tools

#4079 Add hemmelig to Pastebins
  README.md
Labels: addition, reviewers wanted

#4089 Add Appflowy to Task Management
  README.md
Labels: addition

#4094 Add rgit to Software Development - Project Management
  README.md
Labels: addition

#4032 YetiForce added
  non-free.md
Labels: addition, non-free

#4092 Add Grai to non-free
  non-free.md
Labels: addition, non-free

#4119 Remove budgetzero (unmaintained since Aug 2022)
  README.md
Labels: curation

#4118 Remove Actionsflow (unmaintained since July 2022)
  README.md
Labels: curation

#4115 Add Fasten Health to Miscellaneous section
  README.md
Labels: addition

#4112 Add Sunshine to Games - Administrative Utilities & Control Panels
  README.md
Labels: addition

#4121 Remove EdPaste (unmaintained since Jan 2019)
  README.md
Labels: curation

#4096 Adds Graphweaver to Software- API
  README.md
Labels: addition
