Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-02, with the labels that each got.

#3537 Add Answer
  README.md
Labels: addition

#3538 Add Phorge
  README.md
Labels: addition

#3574 remove horahora (repository access blocked by github)
  README.md
Labels: fix, curation

#3540 Adding chowdown.io to recipe management
  README.md
Labels: addition

#3576 remove discord bot dashboard (the project is archived)
  README.md
Labels: curation

#3552 Add copyparty to Web-based File Managers
  README.md
Labels: addition

#3561 remove SharpPaste (unmaintained since 2019)
  README.md
Labels: feedback needed, curation

#3563 remove Hapttic (unmaintained since 2019)
  README.md
Labels: feedback needed, curation

#3564 remove pb (unmaintained since 2020)
  README.md
Labels: feedback needed, curation

#3565 remove Re:Backlogs (unmaintained since 2020)
  README.md
Labels: feedback needed, curation

#3567 remove Episodes (unmaintained since 2019)
  README.md
Labels: feedback needed, curation

#3568 remove Jmz Homeproxy (unmaintained since 2021)
  README.md
Labels: feedback needed, curation

#3571 remove mkaczanowski pastebin (unmaintained since 2021)
  README.md
Labels: feedback needed, curation

#3569 remove oTranscribe (unmaintained since 2019
  README.md
Labels: feedback needed, curation

#3583 add demo link to Krayin
  README.md
Labels: enhancement

#3553 Add mosparo
  README.md
Labels: addition

#3489 Add Matchering to Automation
  README.md
Labels: addition

#3601 Update fussel's description. Include demo url
  README.md
Labels: enhancement

#3573 Add 'QloApps' to 'Booking and Scheduling'
  README.md
Labels: addition

#3603 Time tracking intro: employees → users
  README.md
Labels: fix

#3611 add demo link to ZenTao
  README.md
Labels: enhancement

#3591 Add Bencher
  README.md
Labels: addition

#3596 Add Red Eclipse 2 to Games
  README.md
Labels: addition

#3598 Mail Transfer Agents: Add DMA
  README.md
Labels: addition

#3613 Add Inventree demo link
  README.md
Labels: enhancement
