Repository awesome-selfhosted/awesome-selfhosted, pull requests merged in 2023-03, with the labels that each got.

#3588 Add PocketBase to Software Development - Low Code
  README.md
Labels: addition

#3599 Mail Transfer Agents: Add EmailRelay
  README.md
Labels: addition

#3609 Replace SickRage by SickChill
  README.md
Labels: curation

#3604 remove stikked (unmaintained since 2019)
  README.md
Labels: curation

#3605 remove dogbin (unmaintained since 2020)
  README.md
Labels: curation

#3608 remove ytdl-webserver (unmaintained since 2019)
  README.md
Labels: curation

#3622 Fix EMQX language
  README.md
Labels: fix

#3551 Add Hubleys to Personal Dashboards
  README.md
Labels: addition

#3636 Update `umami` demo + repo link
  README.md
Labels: enhancement

#3640 Fix order, move 0 A.D. before A Dark Room
  README.md
Labels: fix

#3644 add `⚠` symbol to searx
  README.md
Labels: fix

#3660 Fix "SourceBans++" category
  README.md
Labels: fix

#3664 remove snippet-box (unmaintained since 2021)
  README.md
Labels: curation

#3665 remove reduc.io (unmaintained since January 2022)
  README.md
Labels: curation

#3490 add "Gramps Web" to section Genealogy
  README.md
Labels: addition

#3513 Add Lago to Money, Budgeting & Management
  README.md
Labels: addition

#3572 Add Pingvin Share to File Transfer - Single-click & Drag-n-drop Upload
  README.md
Labels: addition

#3610 Add LibreX
  README.md
Labels: addition

#3631 Add Lenpaste
  README.md
Labels: addition

#3659 Add Hound to Search Engines
  README.md
Labels: addition

#3677 fix: correct a typo on superset description
  README.md
Labels: fix

#3671 move motor admin to Software Development - Low Code
  README.md
Labels: curation, enhancement

#3630 Added Mathesar to "automation" list.
  README.md
Labels: addition

#3634 Add Stalwart SMTP to Communication - Email - MTAs
  README.md
Labels: addition

#3661 Add Mistborn to Self-hosting solutions
  README.md
Labels: addition
